# .sops.yaml
creation_rules:
  - path_regex: .*.yaml$ # Apply to all YAML files in this dir/subtree
    # Or be more specific, e.g., 'kubernetes/.*secret\.sops\.yaml$'
    encrypted_regex: ^(data|stringData)$ # Encrypt Secret data fields by default
    age: >-
      age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
