apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sonarr
  namespace: flux-system
spec:
  interval: 10m
  path: apps/torrents/sonarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      BASE_DOMAIN: ***REMOVED***
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
