apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: web-services
spec:
  chart:
    spec:
      chart: homepage
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      version: 10.2.0
  interval: 1m0s
  timeout: 15m0s
  valuesFrom:
    - kind: ConfigMap
      name: web-config
      valuesKey: BASE_DOMAIN
      targetPath: BASE_DOMAIN
  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                HOMEPAGE_ALLOWED_HOSTS: ${BASE_DOMAIN}
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: ${BASE_DOMAIN}
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: thefoss-le-prod
          homepage:
            enabled: true
            group: "Services"
