apiVersion: v1
kind: Secret
metadata:
    name: mirrors-config
    namespace: mirrors
type: Opaque
stringData:
    BASE_DOMAIN: "ENC[AES256_GCM,data:KFptBjliA4whkhQ=,iv:nrm6So9xS9rSvsbIjCRZ2DmZ9vwRaxwNFgrnJlFLZnA=,tag:hMAqYG+x8nrIYT43YQfRnA==,type:str]"
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNG1tQ29yREU2Y3lEQVlV
            K3p0U3BzSVNnempGR3BLSXQ1YnEzTUhQYlE4Ckg3YWtCZWRRTzFzSWZWLzRjU1cr
            RmFqbnJ1WGd0R1JGL0FGblVEa1g1ZjgKLS0tIHFXTlhYWFczcmNEZ0pVclB0Qmdr
            Y2tBUXViTnVnVStWWjJ3NWhMT25iakkK14bLz+eYPT1P/3FCh0RJwM1teKVElCd+
            tysLSoPd/GDcuDvHcAP0CJSxlSFoYg6wWff6ODyx2bA1xidvK1VA4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-05-30T15:51:32Z"
    mac: "ENC[AES256_GCM,data:Al6LpgFrX4f84q0zZLUha3zRvLePjx3CCZkrLEzr+PpJBaAwsOlp5gXr9p6nCOs6isaFpI47ipZATxC5+HD0C/xprBFGANbxuCpgStmjsXUh4WHsnfvzqYiodxoKfHYWtlA0Z9rPOpu2s2ylWSMigiXqAuWB/uH96aLke/2OdlE=,iv:1oZ2bx/6uUKg2GIiuNS2nR0BTMqU8BJ+UdfanSrwznU=,tag:B7WueH8bzAt33L2nbOkzfA==,type:str]"
    version: 3.13.0
