---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: momentum-day-trader
  namespace: finance
spec:
  chart:
    spec:
      chart: ./charts/generic-npm
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: cluster
        namespace: flux-system
  interval: 15m0s
  timeout: 15m0s
  valuesFrom:
    - kind: Secret
      name: momentum-day-trader-secrets
      valuesKey: GEMINI_API_KEY
      targetPath: workload.main.podSpec.containers.main.env.GEMINI_API_KEY
    - kind: Secret
      name: momentum-day-trader-secrets
      valuesKey: FMP_API_KEY
      targetPath: workload.main.podSpec.containers.main.env.FMP_API_KEY
    - kind: Secret
      name: momentum-day-trader-secrets
      valuesKey: APP_URL
      targetPath: workload.main.podSpec.containers.main.env.APP_URL
    - kind: Secret
      name: momentum-day-trader-secrets
      valuesKey: FIREBASE_DATABASE_ID
      targetPath: workload.main.podSpec.containers.main.env.FIREBASE_DATABASE_ID
    - kind: Secret
      name: momentum-day-trader-secrets
      valuesKey: VITE_FIREBASE_DATABASE_ID
      targetPath: workload.main.podSpec.containers.main.env.VITE_FIREBASE_DATABASE_ID
    - kind: Secret
      name: momentum-day-trader-secrets
      valuesKey: ENCRYPTION_KEY
      targetPath: workload.main.podSpec.containers.main.env.ENCRYPTION_KEY
  values:
    image:
      repository: fossum/generic-npm
      tag: latest
      pullPolicy: Always
    workload:
      main:
        podSpec:
          annotations:
            fluxcd.io/git-repo: "flux-system/momentum-day-trader"
          containers:
            main:
              env:
                PORT: "3000"
    ingress:
      main:
        enabled: true
        annotations:
          nginx.org/websocket-services: momentum-day-trader-generic-npm
        ingressClassName: external
        hosts:
          - host: trader.thefoss.org
            paths:
              - path: /
                pathType: ImplementationSpecific
              - path: /vite-hmr
                pathType: ImplementationSpecific
        integrations:
          certManager:
            enabled: true
            certificateIssuer: thefoss-le-prod
    persistence:
      app-data:
        enabled: true
        type: pvc
        existingClaim: momentum-day-trader-pvc
        mountPath: "/app"

