apiVersion: v1
kind: Secret
metadata:
    name: momentum-day-trader-secrets
    namespace: finance
type: Opaque
stringData:
    GEMINI_API_KEY: "ENC[AES256_GCM,data:3aUCNcfyzzMBVZ0/me31u9hz/J2jGeADS2RwbiQvyZ0/rN+fjqZl2ZAEL5lptpTXelNWhGI=,iv:J73kWZ1rTpiFyL9xJhlLlteL3KewRNgA8+WEmQIFQpA=,tag:hgAe/ET+GoKPXJkiY/pPFw==,type:str]"
    FMP_API_KEY: "ENC[AES256_GCM,data:wx8nlAjZSLtMPuV21ujc2v59lGyKoVGO6331wP/wDHY=,iv:Wpp+8UAwtBS8ow/N6djDpfeFEaqyk030UO9QKRvJ2Xc=,tag:KIsmqdvSnSRyIP5JCy1IKg==,type:str]"
    APP_URL: "ENC[AES256_GCM,data:JjJ3dbt/ERTkBK+r53VSkZIOaUwsYCIjUVc=,iv:GtKHMrh53SITRDhtU2Z4mX9paOsSVzisTGxaAF4Q9Dg=,tag:2uUdDNRD788qT8B9/cwK5Q==,type:str]"
    #ENC[AES256_GCM,data:FKS/Ltha40y7+/ox5alQTaAfGObA8KOt6KxdUiD98imqetlJRW9McZLL88OAkl1Kf0HE7Y5zptMj5HaE1TWLRuSa8GVK,iv:IBF8MTocrSqmNDta59W3aJysnPJSzIuvxxBuibCC/eo=,tag:wBIw1oEJLLpzD4osK+T0FQ==,type:comment]
    #ENC[AES256_GCM,data:BBXnA7tpsIMbKdLnm+9d+hlu/bXvaw6tAaIiuoT0mlbYcQQuFoIVwjPHk2+q8SC6Lq27i4rf5PR7sWTNsQhWkd3M8VrkDE8H3ZY=,iv:47wva9mjKhNOVQAVy3skSDpPYsSAAXtjjmjKBhnIhPg=,tag:r1NR63kUtIDm7qozQUlxRg==,type:comment]
    ENCRYPTION_KEY: "ENC[AES256_GCM,data:cFarvCnHXyIE0BbLmVvp6MbTJx94GgqE8b6ACjGvhx+zXDjX5n7zb+3HoBMSvh6OT1FXwEDxxNxURuF67bFMWQ==,iv:0bXWcy3ENwoJrOQL1qaJ5kXtGrp4CGOrIwfO/oy4NeE=,tag:XTXickjtdtza61aj7lYgJA==,type:str]"
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTG1EMzZxeVFlMjk4Y0Y0
              YnoxTmRYVkk3R2lQbVFzSld1bHpRZFZYalFVClVmcWhhQ0VFVkVOeWt1TGFDcmtS
              Ymd5UkRBTWNRejZGeHl0ZG83bVZSUTgKLS0tIFhFd0dNRHFvYVNVN3hQaDVZVGNN
              RU93UWlrZ3VPbjhlUUpqSWdPVFpSeDgK0FwM5H4wqbUUP01SSapTZQGAzQewpBW1
              0VvA12SUILIUievkhB8CV5Xr1/8vpJYI3OMunDNizlJzmkiE9A5dEg==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-23T00:39:35Z"
    mac: "ENC[AES256_GCM,data:VNcwHmyYD24d5GI6+ABtxZK5Clq+xCbxf6vuYPEfXd6FwK9CcZxVSp+Zdu42vDbKWB37mRllLiB7bvdBrBIJaa3pB4acNkq/0prEO2csUVjiG9n4Xid0Uaye0rpVlLkUq8FW1ADunnhyR1f051CWjtmyi/A9AtQ/TphvbeMRDR0=,iv:opXc/YZnF7DCN7wssBNRLgzmd93qT4QGY8eDJ7ZA/bo=,tag:nQ43MikHNESu9VqYQdpbrQ==,type:str]"
    encrypted_regex: "((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))"
    version: 3.10.2
