---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: momentum-day-trader-pv
  labels:
    app: momentum-day-trader
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.10
    path: /mnt/local-raid/home/ericfoss/development/momentum-day-trader
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: momentum-day-trader-pvc
  namespace: finance
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: momentum-day-trader
