apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: torrents
spec:
  interval: 15m
  chart:
    spec:
      chart: sonarr
      version: 23.8.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  postBuild:
    substitute:
      BASE_DOMAIN: ***REMOVED***
  values:
    TZ: America/Los_Angeles

    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: "{{ .Release.Name }}.${BASE_DOMAIN}"
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: thefoss-le-prod
          homepage:
            enabled: true
            group: "Torrents"
            widget:
              custom:
                key: "${HP_API_SONARR}"

    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 1Gi
      media:
        enabled: true
        type: nfs
        path: /mnt/local-raid/no-backup/dvr
        mountPath: /media
        server: truenas.${BASE_DOMAIN}
