apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: torrents
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: enabled
spec:
  interval: 15m
  chart:
    spec:
      chart: sonarr
      version: 23.8.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: torrents-config
      valuesKey: BASE_DOMAIN
      targetPath: BASE_DOMAIN
    - kind: ConfigMap
      name: torrents-config
      valuesKey: HP_API_SONARR
      targetPath: HP_API_SONARR
  values:
    TZ: America/Los_Angeles
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: "{{ .Release.Name }}.{{ .Values.BASE_DOMAIN }}"
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: thefoss-le-prod
          homepage:
            enabled: true
            group: "Torrents"
            widget:
              custom:
                key: "{{ .Values.HP_API_SONARR }}"
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 1Gi
      media:
        enabled: true
        type: nfs
        path: /mnt/local-raid/no-backup/dvr
        mountPath: /media
        server: truenas.{{ .Values.BASE_DOMAIN }}
