apiVersion: v1
kind: Secret
metadata:
    name: media-config
    namespace: media
type: Opaque
stringData:
    BASE_DOMAIN: ENC[AES256_GCM,data:tiHHZqYDiqQRuUA=,iv:LB8jQPD9eOk+KXpnkwdbfyTsueyILXxQ3q5vhE6Cdc0=,tag:R44NRjGGUfDY2jjSqqzIpw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWXFZVzQ2YUsrTHpPTitr
            N01NVFZST0JsOTBJcFE3MTMxYWF3TGZiV21zCm9jd1RXdGY0RHFzV085MjlJQjkx
            dVpnOG5sTzV1WTZNazZtWU5mdEJ6OG8KLS0tIE5OVFRqSHppWUJsRzc1ODFDVlFw
            TElqL3p6aHNJNnRWQ0J3Zlk5c0lEWlkKuvzTS5DCqwRoYIYIRfUSkl2nCR5p2f/T
            FjDF7zse/jpwgIq489kARVHfNkznxFWj+F8DoAFFWVV+7Ly5Gq0WlA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-05-30T15:56:33Z"
    mac: ENC[AES256_GCM,data:Pg9DSzR5asdWve9lnDzZJbWymdBiiZQ5Yy51MwMj+Lro8PbT/jrGz515g3ifwcVylcpywNoigy1wh4LqNRDW6IMdpg8YpPjKeorkq68wcnezTso5AMLgOFsCL3Vh872Fncmz08yan+pWWMCh69W8Qs4RlU9FTpSrQzqyVyrOOWY=,iv:qxctPGBC0Q/ISJTLsAeSm0K2KdoDw1dOmoLqDEzQqkw=,tag:Gez8axeTHZ/5nRW4Ass2RA==,type:str]
    version: 3.13.0
