apiVersion: v1
kind: Secret
metadata:
    name: media-config
    namespace: media
type: Opaque
stringData:
    BASE_DOMAIN: "ENC[AES256_GCM,data:tiHHZqYDiqQRuUA=,iv:LB8jQPD9eOk+KXpnkwdbfyTsueyILXxQ3q5vhE6Cdc0=,tag:R44NRjGGUfDY2jjSqqzIpw==,type:str]"
    HP_API_PLEX: "ENC[AES256_GCM,data:18OuG/TGpHTg6GR+7cbtz9q27Mo=,iv:uofEPFRmW3AtE3KkSrArkqs5rbFWpanBPNAAyQlJ8go=,tag:D2ZM5TSx+QaI+LClhND9nQ==,type:str]"
    HP_API_JELLYFIN: "ENC[AES256_GCM,data:ButT4uTjBJCYYzTFdb4+V66AmR/XDSFYVcUhegl4KEE=,iv:5C6R8rvGQEz0Q5bsHoAdF9WP+9gizg48E5jcpeut0Ps=,tag:QT8Zwz96SD6bwPfeSiFuzQ==,type:str]"
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWXFZVzQ2YUsrTHpPTitr
            N01NVFZST0JsOTBJcFE3MTMxYWF3TGZiV21zCm9jd1RXdGY0RHFzV085MjlJQjkx
            dVpnOG5sTzV1WTZNazZtWU5mdEJ6OG8KLS0tIE5OVFRqSHppWUJsRzc1ODFDVlFw
            TElqL3p6aHNJNnRWQ0J3Zlk5c0lEWlkKuvzTS5DCqwRoYIYIRfUSkl2nCR5p2f/T
            FjDF7zse/jpwgIq489kARVHfNkznxFWj+F8DoAFFWVV+7Ly5Gq0WlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T16:26:34Z"
    mac: "ENC[AES256_GCM,data:Hj3IYR+tuER2FQuo4NADFFlj1LXnGBoXraE95qTzThuhEJfuM13dihdmrPytHRE7ur7PoUv79y5t7TDqlZLP/9haymxZypo7AkIW2YGtqc//lKV89rm3t6Ha9mBGLmYydtYbe1XD42HKwGHJcRPQGrVyUhCGeicALlL2VXyEJ9E=,iv:w+f6laxbeMvxaFaxwYh8eE2TOTlF+nOavBvtpvOBgx8=,tag:j5xWkGI+LGCEBTJ3pKk0Tw==,type:str]"
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.13.0
