apiVersion: v1
kind: ConfigMap
metadata:
    name: media-config
    namespace: media
data:
    BASE_DOMAIN: ENC[AES256_GCM,data:Yl02XNC0MZcCAaQ=,iv:wwxH/VOOGuc3qPKMee0CEWbXJJObayq6waGRdgqNXDU=,tag:uc0SV/Ckwyg/2zBkPIirLQ==,type:str]
    LOCAL_IP: ENC[AES256_GCM,data:2urfKie6tQPWz1fS+w==,iv:QzyEwI31eZOm5i8ApqMzndIW0ZpYzCq8VP1EmTl2AvY=,tag:2grYIPbM5jWqHHIBoKenbA==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSVdJd3dVZVY5YWF3Zkpt
            UFRsNEoybmd0T0c4VGMvclNKZ0JQVFJkb213CkVvN051Qm1DU3hkK2JIb2s3ODlj
            SzBNR3N5ZUZOdjBSUFhEZmRaTy9Cc2MKLS0tIElWWFRDTEdiTk50RUhQeUpMT3Zm
            M2ZBVmVxZUVmN2JTMkJURFQwcTBIT3MK6dsZ2683DIHq1lyiroM2O0Ml0pIEyLQz
            B1FwYHpM2pcmwD0wvzJw89oPspzshpVjgFix6XDQ5z516MtMVw/HVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-26T14:47:31Z"
    mac: ENC[AES256_GCM,data:C+8DNvUS81MubPtlStip3HvlQqqF5qHWAGwQ2Do3Jo4iG9s0FzlKACSxeOUKXZB0vuagz/K6ozZjT3NHUNWLB9rj5wu/mLXSyoElitQng5rs+arcFcOpEA8XW4qygQ8gl40aTQio6K2zk1DQ4X7Of/JUQYfT1nMBMb8mYtVeKc4=,iv:Of/tBWCCM1jMB3DyULPFpiIklVk0zOvnkZW5QhJlw2s=,tag:GvUfs2knoevPnYXFhIqWBA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
