apiVersion: v1
kind: ConfigMap
metadata:
    name: torrents-config
    namespace: torrents
data:
    BASE_DOMAIN: ENC[AES256_GCM,data:2cr64xEl9xQRx9Y=,iv:dgANOB6VYaSkH86ZoLPJb699BYHwQo124QKZ0tWfYh0=,tag:/BULZnG3iT4yd0b8tDGL0A==,type:str]
    HP_API_PROWLARR: ENC[AES256_GCM,data:r/37pdMeexhJWPHEIZAndyzUZCLJsu47z2/k1bfM5OM=,iv:v7FaI6UIWMN2YA3V0YhY0036hmE+qZkxc0z5rh6/mis=,tag:aO90/hbxBT8aqlf6BVvHLw==,type:str]
    HP_API_RADARR: ENC[AES256_GCM,data:4LZEnqDQrykYWwrtUF/wBiAVnGZauvB6zXVefcIWWw0=,iv:rjHz+sMvujAFeEtXlFJf+zZoYUuCld3nMcM3LuhKfew=,tag:nA4/sopzmK6Nb1jzuBcn3w==,type:str]
    HP_API_SONARR: ENC[AES256_GCM,data:2epFbEV4+N/WUPKztmseAw2Vlp6N8d3I//wqdXcv77k=,iv:m59Hr2ES+K1o73GsKZD9HKfUBBf8Hn1q7Zrdt/pcLfc=,tag:Csr232t98YSLeIAxfrMLpg==,type:str]
    HP_API_READARR: ENC[AES256_GCM,data:ylTbmWRloSrHl3MOcBDBQ5zQlhsqbOlYebfYOoS91lo=,iv:TYUP/Ee8LRo198uSyaA8XkAWMiJrK4Jp8N+6fLV6evQ=,tag:5NFEvj/z7iErIP3D3LZHxQ==,type:str]
    DEFAULT_SUBNET: ENC[AES256_GCM,data:DW2ywB+Pl2VGB+gFBaU=,iv:8ZU1y8rM2GUM2zW4YEtTVUgoV8BiVjHb389s/Du5Clk=,tag:bvrOMRxEWZAqzuJgLBIi/Q==,type:str]
    SERVER_SUBNET: ENC[AES256_GCM,data:+nF3dhFg81AdNKItsSI=,iv:H/efFg4iSupokimdz8OcvDMCzJJaE/ii7e9m7fPbIQg=,tag:Hx2W+z/FMRK15DVvDF5vIA==,type:str]
    KUBE_SVC_SUBNET: ENC[AES256_GCM,data:FzBVeGVcKv9EwiP5,iv:7qWbIYfpTOKoQLFlaN5oFxd6jgvtaFQdvD92OUr4p20=,tag:f9OF3Eda/8U9j0c9Z9ChFw==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:B3L6SB2Qhg==,iv:MJgZswvOy+ntaA/HPrx4l2PWZaLv8qN2o5mWSAvI5g4=,tag:cvAVCLhPVCRcpMSRpfLUhA==,type:str]
    VPN_USER: ENC[AES256_GCM,data:fGK9p5owTsA=,iv:8WPZ/WCAaRuDs0LyeqaDc8wFkiqLuRY5EvNaovIYxK8=,tag:LFQqx4r/FlKKIod2Hq1j/g==,type:str]
    VPN_PASSWORD: ENC[AES256_GCM,data:omyttfdxo2nnkpLt,iv:5zYsCPn5AE/QM9CNyfPg0J1e9EPBSBwTmU+QHa/Y4hA=,tag:LynaNOw70BPIlVz+L90DfA==,type:str]
    VPN_REGIONS: ENC[AES256_GCM,data:HyBRa3L/lCu+fQ==,iv:ZxtYKhNdyyAGXgo4hsRlaVlW0LBnyxmF23U6EUNdNCM=,tag:Ec9hL+3UQ/nnHXphDa3HIg==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYnR5WjN2eDZobVMyY2JB
            dHRCRVlpZUN0SVRqcGNsWDhCeEswa2RUWnlFCnJmNjBYOWxISkhRaWJHTUJnV0Ro
            TXZkYTFnYWZJVFQyMmZSK2VtRjVhS0UKLS0tIENWbStIUGxNOEJpZFVxNUJuRDJz
            bVVld3dBQlJnaEd3NXdWeUw2SU8yRWcKhEttwRzm8lnvIYW7Co59kR7cA2WsqHP1
            Vt83HISjSs+eEJv+f5w1hCnNrNrILsYA1lPpM7yjTN1TdZ0X7bnXXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-18T03:49:58Z"
    mac: ENC[AES256_GCM,data:QQNxN+7KbBhhI9fi6Q+RwDf6cCr5660r/HtVeVvZbUvFLPaeqPOQdU4Zoq0yfj7RJ+VwXI247hgB66QIvO2MuQNnurTGoH/ou4B++lC/LTrbCaYpYikXWFezaYGFbrf3NDjMz+M1RP9rxbPUMolChFLn140cYuN6iXPz3jiDqUU=,iv:QqgiCuctagb3Ao/PHj38Rf4CVR+EfbHTqvqdMx77QTU=,tag:AVDTyfGq91v0Ds8spyWDLw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
