apiVersion: v1
kind: ConfigMap
metadata:
    name: vpn-addon-config
    namespace: torrents
data:
    addons.yaml: ENC[AES256_GCM,data:mba4SLUDqAeOaYTetvWMK0DGVx9jLi1r213DtF86Vfac6BSVlvdGC2BygNjFkI/nSFvnJbu5dee5xOEfWQ705FAHmmQ99VAiVeHOdHfjULVmKcEgtAiX+PDYVw92GlwndrJxKphZpUfhOiUmRYQWXxOCoW/8KjkQA7g194U1u12CV0FpLBZ+K+ALPZgVcMBbXBETBRMZjwpC7OgIjA7Ow5Z5GVU4McU0RfavXesvtAKuPVKndzxppTMl6RF5z//gNkSPV/c29jCzCFOzy7GKZ6L8ws2EciRgXgl76XtoleHwtKQQaPjqiQtQuD/tToU1w0qbTn80M4rR5eIncEJ/AvfNHwlKCwc5uVACwjLECaBSRjkRfkPBj0nt/+yW+dTlm7Klf1W/84oEHVEbIb+pKH77SWY6RBYy0HHihgKrnsBc7JGSfIiKIW0SacDpI3XkvFWz+MFERwSBv/8VynozcQ8ulDRXpzG3HRHO++KgYPXiDeVA2o9G3R/GK6P7QealGtrPXyi7Nx4BApfI5KyHlHjsHLMCpNg0nn0rsT1r9yzgAFd/53fK/0KfhVzmPr68dq75F3Sc/AcLceapBBt7pE6HvJmrzQ3na0FEyB/TdOy2v7pf8ikHChvwIra8qwIElh1pTEWvLY87NxXez6arLpimbrfnRbrxW+rCruD2agDFSGBb6wjOIYzcKFk0lPpsAoW7RHe4ejVI6gXQ/I3pCr1yVhxKRnOr7XzP1Efltc1jK8XgVLRwDTayLt4MsXFy2vpaqSPhCB0NSDU7D4kqtxXgIicCN7vRxOleEXoeKXkLsDV4ABhKdt0=,iv:1H/eS3N9agsG7jQWm2InOsHAPgFTKMS6LtRXrqL38sQ=,tag:Qh335th9fDqhP1i4IbbYoA==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbUIrcDRHMVlZcVVlVmtp
            TzUzRURiOC8vcXVJNWJ1aVdQWGpieTJYNW0wCkVKRjBZRGkrd1hpWFNNZVIrZ0c0
            RlVaVFc5VW5XelJpSGRkcktqUjl5NzAKLS0tIG94dVNFSi9ZYkxZMmxhbzRySVcv
            eDNsaXg4cld6RVcyU1hLa0NDK1VHVW8KPS2GnsToI8R7I++aYsE4n81iPIPnyoud
            Rnlvs7dVczbQ4aTR1QNb1gCiNB0XAHd7jdtoXGJ7ghdiGV4czctHgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-19T00:02:56Z"
    mac: ENC[AES256_GCM,data:DCEzObYBp5nIiFh70R88gGsFB4uLWMCK3xFk5MPmJOzecdG6TXNLIqKUvAgVTIWNWegItxKWPopXruoPvdSo3hw6v2VBtPAVWQ27HrXLvd77Xu1OtSJB6wYjDUjwm7KfsKzRu6YkTg5yNsIlPYCO4g38NwlgNU0+GeLjuf19tQg=,iv:vLM8PDANi8t3lBT4gOHHlTmL5O/zewKzRRPt3cI2Eoo=,tag:E/ll3aGfzOFmdEKzU0RaWg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
