apiVersion: v1
kind: ConfigMap
metadata:
    name: vpn-addon-config
    namespace: torrents
data:
    addons.yaml: ENC[AES256_GCM,data:X83yPAjsX2R2tyn3+8Xkh5/skDdLqh/inEQZ3KG93WRx8m+IAQgrMMynz6mF3xSc/3TBVvhe6HBRGiTlcNyNXmi/gq0GHqweAhjt9EQ/KwyDENJKdi2XZ+lbeU9NmvkuioG/rEZ4H9llSEzW1Q08HLLY14IyD6nsy56gectTCFeIoMB/V1rtoJ/hWvrI0YB4rOmQszLrYyn/EkD3j+6LIDFRn6+QsqyIA4gnyClfJyWe7W6lXpM/z+mMN8zywWkCZKUd1wDhbYsKFD1MpP70YEZv2jLgvIZwKcEDtrONDTzz3/M0ggnvKSvsuS4d3R4+V5C36rGtLfklK1UWMIkVnn7B69R0iJ09aXsL28YPJhxc8vmPIQoGmT/bejcjhIKdzk7gF6Ke/1nI6PrOeNGyC+EZly5puCUsdDV3wtsgvoF62Jq3GrR4oirp+FiWer2AawMuTE1bl+9Llks31D7RQVgWEqm2ZGJPrKy93BjHtLt8lqUxegHbCgU3NPdOjqKrvbqfIfIBRjC+T80H5dcMb2ReOuIewIaiKLmdHt8qgSBJpib3v5uUw+BKYeRk80wJUHd+g3LTH4gus/uYdYwtMQxImn/SrnrwJePLt073PitZ4VBVKrSdjJgnXWgmtCsglUACPFxLsXbz0XW48B16dCr9GZG0LcPB2QlLCQZUCBtD6ZL2saFWIUBZjYUkGcrJpVi9THAFcWRXno5412W/D6UBwP5ZUY6d2rhQX8H4E8Tt/36Mk/u4Z2exDEKK8w==,iv:od0kqpvo4sQv8x9nDYERaGwh/ttQpDQZuWtL8pk1gSE=,tag:iC93h5i+hOcTyfzD+o+gcw==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbUIrcDRHMVlZcVVlVmtp
            TzUzRURiOC8vcXVJNWJ1aVdQWGpieTJYNW0wCkVKRjBZRGkrd1hpWFNNZVIrZ0c0
            RlVaVFc5VW5XelJpSGRkcktqUjl5NzAKLS0tIG94dVNFSi9ZYkxZMmxhbzRySVcv
            eDNsaXg4cld6RVcyU1hLa0NDK1VHVW8KPS2GnsToI8R7I++aYsE4n81iPIPnyoud
            Rnlvs7dVczbQ4aTR1QNb1gCiNB0XAHd7jdtoXGJ7ghdiGV4czctHgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-18T23:22:52Z"
    mac: ENC[AES256_GCM,data:RrQIHWmkFl9i3+ug6dXw/5LwgCL4bkNoi0Kkk6NTNXLJq6o69ZqcISXKhKIZK6whTOxqCcZs5BEj4Odwhm6YzyAaNHPYDimLt96bk4VHN8c6SGAEj31ikrycudrIiSVGQtBAsjEv1ybbIEWKQ0BbJwr95sW2OmcDPW9bQxSppw8=,iv:k4CE/ty49GYnVnPzJjU3zKCbZXFUYQRNA8PU4VuNWqM=,tag:0aLhy5OwOQ7i7TqI6UrBlQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
