apiVersion: v1
kind: ConfigMap
metadata:
    name: vpn-addon-config
    namespace: torrents
data:
    addons.yaml: ENC[AES256_GCM,data:4ZO19Pe3bOFr6SGta70NhWLpx2yqpHt/Y0Ur96zVaVOtHDri/bVK6gaLHdM37Mv9DNsrM7Hab2yeGlta4hURxbE4wklM+9NwY0RyiKke39CNKIdG6v8JBzWqDgLhLDCwpzf4s3JsGINEER0x/oPjM2HMZU+uZQ61zEVDCIUfShSSzNv72Il3pPr+o2cruoii+gnoLsvy39Oy7QwFg9JHM4PR4kAGWoKYrvElzQ0+qeFyDoCiBhkHGjnanlEfXxmxnePtKbIsmStszXoCZLgOsHaj7ofcX1ZZGjqgnpF1lR5uRBO8i7CdRACXvxkbYmcAkpYcJbd3ZLWHVZZa/dfYgIw9WaEnOKqpkrCLm5lHcBngMul3vWNaekMj234J1RKdn3HgybSNxLKgN8lP8fz/Q10bwF6SSNA0ZnO/jTf1yhTGcUa0Ky4hLSFGqyySTXsf+KRIq7/P2/Susx12w3sWohXomOjnKpjJKQthD/KoSoOKqhJivGvqK/hi1AgtGI2xF18GdKPZHkEjkq7mbJt0Akw9XFUVlvlNnctHKiEC1V198g796XOgVqFFzk4n0k4YsvlLFSsjUsPk+chQ0fPMDWN3v5JyfCgjPmMOTM4+x+6rKmgisgCZOHiICj/kvfsX2SEStBLbyaRd+Q57BG1yTyJ0d6MM1840cnfGwBdkulIIVPmipiGTWaQlAPX7+kM0I0nyKTWNukiICBJWny0E8zyG1Tj2b0hwywEbhlU=,iv:04ST2TyN8ftprraqo1PFw56xuH71WuhjodpI4c04sLw=,tag:hwidUAjGEW9KH5CaLrz4qA==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbUIrcDRHMVlZcVVlVmtp
            TzUzRURiOC8vcXVJNWJ1aVdQWGpieTJYNW0wCkVKRjBZRGkrd1hpWFNNZVIrZ0c0
            RlVaVFc5VW5XelJpSGRkcktqUjl5NzAKLS0tIG94dVNFSi9ZYkxZMmxhbzRySVcv
            eDNsaXg4cld6RVcyU1hLa0NDK1VHVW8KPS2GnsToI8R7I++aYsE4n81iPIPnyoud
            Rnlvs7dVczbQ4aTR1QNb1gCiNB0XAHd7jdtoXGJ7ghdiGV4czctHgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T00:08:02Z"
    mac: ENC[AES256_GCM,data:/UfPzBwjiT3O4TuyYYKRnEAJwMhl44udIJfIaknVpMKtC0jkgI8jIfmOGrlKkJjBFeIQ2CSlIVyBqZkvTzjtpNSJ0NWSFXPW67g7On0QRds6S3e66k3dDjpfGb62wWE7IG9HdVYT3sYPLZ4epwC0KKST8bh6TUsURX8W8A3w8I4=,iv:rk8vlE5lNuohZf8iO268DOVh1IcP2NjhShQwx4X/ob8=,tag:kvx4xXPFcsSiXqINum1gBw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
