apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ib-client-portal
  namespace: finance
spec:
  chart:
    spec:
      chart: ./charts/ib-client-portal
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: cluster
        namespace: flux-system
  interval: 1m0s
  timeout: 15m0s
  valuesFrom:
    - kind: Secret
      name: ib-client-portal-credentials
      valuesKey: IBEAM_ACCOUNT
      targetPath: workload.main.podSpec.containers.main.env.IBEAM_ACCOUNT
    - kind: Secret
      name: ib-client-portal-credentials
      valuesKey: IBEAM_PASSWORD
      targetPath: workload.main.podSpec.containers.main.env.IBEAM_PASSWORD
    - kind: Secret
      name: ib-client-portal-credentials
      valuesKey: IBEAM_PYOTP_SECRET
      targetPath: workload.main.podSpec.containers.main.env.IBEAM_PYOTP_SECRET
      optional: true
  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                IBEAM_TWO_FA_HANDLER: "PYOTP"
                IBEAM_GATEWAY_BASE_URL: "https://localhost:5000"
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: ib-client-portal.thefoss.org
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: thefoss-le-prod
