apiVersion: v1
kind: Secret
metadata:
    name: ib-client-portal-auth
    namespace: finance
type: nginx.org/htpasswd
stringData:
    htpasswd: "ENC[AES256_GCM,data:7cGcNJm8veM8DcHfRK/c+sLLp2qggyEMpwt0Tw30wYB+Jcbc78yo+bgPSw==,iv:KZZNXy9nHKOXpBd/Z9pTP2FOs7evu0vliz6+RtCnILw=,tag:8CyyWCuk0+ig34Lm/vCQGg==,type:str]"
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1eit2Y2FFVTRNQkFKK2xj
            QUZteHBxY2tmb2xTZ3pEZG1wa3lTVHBnRVgwClEvbWUxMG9Wa1FZMDE5VE1OMjFi
            b0djNkhxZldNUnVadFFZVTlJVS9HUDQKLS0tIEN0cUxSdmo5NVJDRzcxMENNZTBm
            TXpHdVBvZ2lLeHJhM3NwYkNQZzZKSmMK2WubUwK5Qsi9qwNOGkxDhBIpwrNEU8Li
            06wyCW1T3Lmon0bZgpiCI++Q/vimnvUblU53IWQv9VQebHLPgtrG5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-08T03:59:20Z"
    mac: "ENC[AES256_GCM,data:gIYXGK3umpeqgE3ulE5ax0bFvTYXMOkpfHFYBP9uCNRUyPS/q0AG5r+HZqq4Boi9DhvicMHJPXMke8k6wZx/Bgz62hmHK/zo8DgPlPYv+VwEvIRWUESa5eRD29nGNu1a7YZwzjzKg8f6ml2bNspUQuTgVKyIiN8mlQRoYFEfxIY=,iv:W8MuSUFmLCcp0BiI2nvjgqrKVVpIhhRn5zDvxysUwpM=,tag:6tamqtBw9m2yOUVtPeGc/Q==,type:str]"
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
