apiVersion: v1
kind: Secret
metadata:
    name: ib-client-portal-credentials
    namespace: finance
type: Opaque
stringData:
    IBEAM_ACCOUNT: ENC[AES256_GCM,data:yl6/ogQyY8oi,iv:HnJccywwxCBXhctf4r54A2b6iyhGwZ4qHaQhPA64dw8=,tag:8LFYZOP3wPTUMRfXFJdz9A==,type:str]
    IBEAM_PASSWORD: ENC[AES256_GCM,data:PKjb2iqCJKaJoBDmORUHyfX1CFQ=,iv:6vcHD6Ve4yd08XZpzEBAeN0dzIf5YDeJvEJwuQKAvp0=,tag:lD4vB/zj/LsaW8SeLQ9icA==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aS9vTC9XRHJOWXBKMDNo
            QXNyaG9qMDlRL05ubzBrUEwzaytJZFhvckY4CjdPeFRKUmhTSFBIMnZuTU9EOW00
            TFQxNHpJN1BsNmJnMTlBMXlsbzFkU1kKLS0tIFJLYkNjZnZSallQNUVwenF3cmpC
            cEszb1JJYmw0R2V3eXAvdWtNNDd1RU0KlPHdc3bY4qoZ5jjshjXClPhV08ZdfcRD
            83zcNb4HJG3nC8nqbJvDDP5Gni2kGyCDsQu9WTjaKlDAAuW65mHJxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T22:42:49Z"
    mac: ENC[AES256_GCM,data:FBolVPBIdQCQUFQqpK8Rv1HfEpZ/2EGI0kgJ1QPESZ8Mj6mXX7l0j7GEqqTiijDYlctSkjCiBwaFlC0ntIoGFhd85HsV6+tMBoTw8L/dWiv8Q2IOVlnBI/TZTlvlEF2NofJ07jf8ok2+l/2xjVoUtXUWoiDy8YlauBleXQCfEcQ=,iv:HulKa3lXM+0EcUbaxuWW2efr60hJCmtUUuivuBOO1mY=,tag:UjY+diLJ1LUdvPvzH7DsAA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
