apiVersion: v1
kind: Secret
metadata:
    name: ib-client-portal-credentials
    namespace: finance
type: Opaque
stringData:
    IBEAM_ACCOUNT: ENC[AES256_GCM,data:yl6/ogQyY8oi,iv:HnJccywwxCBXhctf4r54A2b6iyhGwZ4qHaQhPA64dw8=,tag:8LFYZOP3wPTUMRfXFJdz9A==,type:str]
    IBEAM_PASSWORD: ENC[AES256_GCM,data:PKjb2iqCJKaJoBDmORUHyfX1CFQ=,iv:6vcHD6Ve4yd08XZpzEBAeN0dzIf5YDeJvEJwuQKAvp0=,tag:lD4vB/zj/LsaW8SeLQ9icA==,type:str]
    IBEAM_TOTP_SECRET: ENC[AES256_GCM,data:b2TNztb2Hb+WCCulZdrB/9X4WGNZNMB1dqjIjCcPEiA=,iv:ScYBTJjYRK1bRO3hi8tXXRJgxllOsDthOjwSr/5Xzx4=,tag:QGJjZ1FaGUEtdf5qh72HKA==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aS9vTC9XRHJOWXBKMDNo
            QXNyaG9qMDlRL05ubzBrUEwzaytJZFhvckY4CjdPeFRKUmhTSFBIMnZuTU9EOW00
            TFQxNHpJN1BsNmJnMTlBMXlsbzFkU1kKLS0tIFJLYkNjZnZSallQNUVwenF3cmpC
            cEszb1JJYmw0R2V3eXAvdWtNNDd1RU0KlPHdc3bY4qoZ5jjshjXClPhV08ZdfcRD
            83zcNb4HJG3nC8nqbJvDDP5Gni2kGyCDsQu9WTjaKlDAAuW65mHJxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T22:56:55Z"
    mac: ENC[AES256_GCM,data:OoOKSP9wU6EZd8WDng8XFVajQUS811FuMYx/OqAI3OsoDeYICkqquhSUE7+um9Ob20vrThp913dio7byTdD5nu8uD/noZFX7AaneQAx9KEf8eAyGAuCSmMOva7F3jL5nl1q7kttZmEzOz4D1LI03dL5tG7jpZeKNuOddektl5sw=,iv:84nN3g64nLiRDe9xb/GXwVYLc8WaOqLBTdbzSPvLvi0=,tag:0DSDOQ8wgWbfoHJqVmYbbw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
