apiVersion: v1
kind: Secret
metadata:
    name: ib-client-portal-credentials
    namespace: finance
type: Opaque
stringData:
    IBEAM_ACCOUNT: "ENC[AES256_GCM,data:yl6/ogQyY8oi,iv:HnJccywwxCBXhctf4r54A2b6iyhGwZ4qHaQhPA64dw8=,tag:8LFYZOP3wPTUMRfXFJdz9A==,type:str]"
    IBEAM_PASSWORD: "ENC[AES256_GCM,data:PKjb2iqCJKaJoBDmORUHyfX1CFQ=,iv:6vcHD6Ve4yd08XZpzEBAeN0dzIf5YDeJvEJwuQKAvp0=,tag:lD4vB/zj/LsaW8SeLQ9icA==,type:str]"
    IBEAM_PYOTP_SECRET: "ENC[AES256_GCM,data:6jW3838scx8cFeykNLO3AAJmYa5U3+jYMpY4ZmEoTkE=,iv:HPsGIYNV9DDIMwrWKMVhtE7PVQWpufqL3FrqCLI/21g=,tag:nTKGXfytV1LPAAKMqftBuA==,type:str]"
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aS9vTC9XRHJOWXBKMDNo
            QXNyaG9qMDlRL05ubzBrUEwzaytJZFhvckY4CjdPeFRKUmhTSFBIMnZuTU9EOW00
            TFQxNHpJN1BsNmJnMTlBMXlsbzFkU1kKLS0tIFJLYkNjZnZSallQNUVwenF3cmpC
            cEszb1JJYmw0R2V3eXAvdWtNNDd1RU0KlPHdc3bY4qoZ5jjshjXClPhV08ZdfcRD
            83zcNb4HJG3nC8nqbJvDDP5Gni2kGyCDsQu9WTjaKlDAAuW65mHJxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-08T00:13:06Z"
    mac: "ENC[AES256_GCM,data:rvDr+jarjFnrrRa8X+dzQjloHW7t5UnNeFalvEU5ebPnt7Hzol25cRKsCKCv7kAGe1fDVAPGRIzQcViBSsVBUH3YmprvzoQ1RVAYvHQi/rhZ8N2AdELsZ0NI46TnzNwhU8rcngGPVZ+b+AkRerLS37o+EJN/NUkeobCMF+v9evc=,iv:+cbm9Xjx8D/Jzkurc+k/9LOoaKZNDjVnpcPnS0b9csg=,tag:4CqOlvDVzDXgVIj6ZVLfAQ==,type:str]"
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
