apiVersion: v1
kind: Service
metadata:
  name: {{ include "ib-client-portal.fullname" . }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ include "ib-client-portal.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: api
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
