apiVersion: k8s.nginx.org/v1
kind: VirtualServer

metadata:
  name: proxmox
  namespace: web-services
  annotations:
    nginx.org/proxy-ssl-verify: "false"

spec:
  host: proxmox.thefoss.org
  tls:
    secret: proxmox-tls
  upstreams:
    - name: proxmox
      service: proxmox
      port: 8006
      tls:
        enable: true
  routes:
    - path: /
      action:
        proxy:
          upstream: proxmox
      location-snippets: |
        proxy_ssl_verify off;
        proxy_ssl_server_name on;
