apiVersion: v1
kind: Secret
metadata:
    name: driver-nfs-config
    namespace: storage
type: Opaque
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:+C98s7Bh4E3y2XuG168n8Sni+RZ76hmQM1FSBnwwHmBbMlEGvbZ8JQUUvP0Fi20hO8MtZ5TzXS21mFOvrIv9XiTaHweDibGAhf49dQnVVYHOAUBmtieEtg8lMt1N+9ZN6nX2UeC1V7Mdj8nPtAKci+UxkdKb+OCE+YqD2v0OGl35VzTRW/QjFBcJ4opGg9/MwfQJpY5owRcMTD2MYZTR5NLrUZRsaZKGIhaYWEF2167zaGXyvgE6wqnuE5lU87X4TJC6idPZVzgEkBS6Y3vAVEScHg5BnVSzntMPZSEd2VbBLXhH/gFHvPxbLceZ2zj/SRx6Wa/ICrRwWFobN7Y4/3fmgBCejIa261Pu7NGz6sXhlvYyfIgKuzYx9WACak1SwLz0Mw4ngXnrhMcgAj+6WjaceSJwOB35+1jBvPrgpmyIoKukn/DCFDTomw1Z4o5ALWjHgkDUsJWLkFz4B44l64V1oLXHxVUpR+9lUYD7JkmqOIr+Gn7pWd/nXPZpimVk8wEvKxh+jOCvGSmdvt+HEyqbToVDXjrIQSUnl/4WygopaF2NIb0V+LswilFFOCiyFNGSwc0fWKnUrj/gdcNoSxtnjWBx0Pw6iF7zk7Q6fvURdQswt8X7MP712uoo7OtZqiCKpJPr96ta4AFZGktnv9iSDOQyD8BXIFovQZPvU64Bz9xLbi9nccfdiytUA9W5tQ2S3T92PSmPhPgVB2koCrYDzm1P08Hn2hZvh4XnxQM/LHDtuffd66Z5quqClErJT6Zp9y1+BUWNPVqZMkMCsb1wNhqqvL8jdLJNZYvIe5MSjfzoI53foA9kLXes6dvvZo7X7/iUoMJluKnkTxE0bnywnQ4CgxsIkdUZehJsqidIfJWH+1eQJhpRMCBOt7OraJQ32RxFQhmydvN9+v2FNA6NhywPPxJ1PCTFfeOGGHrloA3zskWyIdPFEuhIIOCKUDHGangdgds=,iv:dTTvHYakG2nlZ0NIYMnU/77WKLO0RJth2uFmdtZW1eQ=,tag:yuPT2AMDAxXNS6DDrTGgLA==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWnJra3diaWxxTGorWWFv
            cE5BeWNxYjVRMEFndkVIWnFhbzNiNzg2bEhBCitabUh0L3ZxQ2gvNGdMZTJGY3Av
            bkFVSjcyMUUxSUFjKzFkNDB2Rkc2ekUKLS0tIFBDM0R0bWtsZm9aTzU2STJjR3NW
            a3RUeUd6Z1dCTnp3d2F0YTlJM29JWGcK9wcid4MsVEETBhNVumCSxMGllTSyefmB
            4JLxizUJOdByneiKD9C3t9fpghKLUKW0sTkjxZYEIUvdDOe/BZ7hvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-25T19:43:03Z"
    mac: ENC[AES256_GCM,data:7uYgJ/PZyP0tCJW1Ql/BmrItjANHR4TzGmdIxO8HOECiUDFKKeIT7KsCid4fcf7D04bPV/HAzxxJgtaPZR4Z76DJXAcDn1d/O1Zfej0UIH/EkK0kzsHpwqrpQx9r25sQQLipRYDbFou9tkPar6HwgSGDcQ82Vvi+HKU33H5HAGE=,iv:qj7ZjXDZgu2twadhwW9k9SpsaoHWdHJRFm5n92ANwyA=,tag:/1xxbTsvSydcvPZak+IbKw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
