apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - driver-iscsi-config.secret.yaml
  - driver-nfs-config.secret.yaml
  - truenas-iscsi/ks.yaml
  - truenas-nfs/ks.yaml
