# In your kustomization.yaml (e.g., ./kubernetes/flux-entry/kustomization.yaml)
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# ... other resources, bases, etc.

patches:
  - patch: |-
      - op: add # Use "replace" if the annotation key already exists but has a different value
        path: /metadata/annotations/storageclass.kubernetes.io~1is-default-class
        value: "false"
    target:
      kind: StorageClass
      name: local-path
      # Optional: specify apiVersion if needed, though kind/name is usually enough for SC
      # apiVersion: storage.k8s.io/v1