apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: storage
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:/FKNRMUrnHh/KO6a0GGHq8tOsF0=,iv:3eK87akJTHj9/ln9YX2JJnVsFA5M6CTybJS3k6Ph550=,tag:Cg/C6O+XDy8TEGhygxFW+A==,type:str]
    MINIO_USER: ENC[AES256_GCM,data:WSRFNWexZXE=,iv:4jSdHiA9fmITIjEal75NnBtgdoRQp+0aSMJ1tZcyPRo=,tag:Sjwhfar//POBorIXFZFYmA==,type:str]
    MINIO_PASSWORD: ENC[AES256_GCM,data:LAOFhB6Q8ET41AiMokNi45uSv/s=,iv:RVvBGuwoNvdmlaQaAVvtrdgRq29YI5Li2SsmnVDjulY=,tag:TaWtkwD+O8o6wYPE1TLoRQ==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Uk5lR2dWQzQ5RlQrTVlN
            OVZpVVVFUU1ySEtGRjVSSVZheHBhaS9jZTFnCmR4QkJJa0RWcTdJUThXTkVCQ1Mz
            M0p2cXFxZlcwV2pYTVJIYVEwOXZJQnMKLS0tIGdObXpJNmVoUlcwZnhUNDVJTlEx
            YktCaThRQWZiZVBjOVIyNWQyUWcrODgKj698gx4gy/ommsoLYM6uew1C3qedWUHq
            Bzi4lhXZWMbHQtS6meMhwMYbVWQeoVI/lhEhSzqZ2KMC4UVXzhkwKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-10T15:59:42Z"
    mac: ENC[AES256_GCM,data:a8NC9yAA26B4wNYEt4ocWSazgiXaqHSulAerKQj4rZ4DddJuhwM5qQKtTdrQpGZZRRHxaboSaXzmIzvp9gWw3Vri0jw9UdRtjaR+QgZjFuyR1fiuC7R9gwA2rT1KXb8J04KxzuyggEooEpN/wANvIbHFULlb9/10o6Quu/gEpnw=,iv:jsXrF32GhEunHiXGcMeog+uHdcmXlG8jvQaU3TfeN+c=,tag:KtRQixsSB6E7xyr0P3FMKg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
