# generic-npm Helm Chart Values (TrueCharts common library)

workload:
  main:
    replicas: 1
    strategy: Recreate
    podSpec:
      containers:
        main:
          enabled: true
          primary: true
          imageSelector: image
          env:
            PORT: "3000"
            PULL_REPO: "true"
            # BUILD_APP: "true"
            # BUILD_SCRIPT: "build"
          envValueFrom: {}

image:
  repository: generic-npm
  tag: latest
  pullPolicy: IfNotPresent

service:
  main:
    enabled: true
    primary: true
    type: ClusterIP
    ports:
      main:
        enabled: true
        primary: true
        port: 3000
        protocol: http
        targetPort: 3000

persistence:
  app-data:
    enabled: true
    type: emptyDir
    mountPath: "/app"
  npm-cache:
    enabled: true
    type: emptyDir
    mountPath: "/.npm"

probes:
  startup:
    spec:
      failureThreshold: 600
