apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ark-server.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "ark-server.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ark-server.name" . }}
    spec:
      containers:
        - name: ark
          image: {{ .Values.server.image }}
          env:
            - name: SERVER_MAP
              value: "{{ .Values.server.map }}"
            - name: SERVER_NAME
              value: "{{ .Values.server.name }}"
            - name: SERVER_PASSWORD
              value: "{{ .Values.server.password }}"
            - name: SERVER_ADMIN_PASSWORD
              value: "{{ .Values.server.adminPassword }}"
          ports:
            - containerPort: 7777
              protocol: UDP
            - containerPort: 7778
              protocol: UDP
            - containerPort: 27015
              protocol: UDP
          volumeMounts:
            - name: ark-data
              mountPath: /ark
      volumes:
        - name: ark-data
          persistentVolumeClaim:
            claimName: {{ include "ark-server.fullname" . }}-data
