apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ark-server.fullname" . }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "ark-server.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ark-server.name" . }}
    spec:
      initContainers:
        - name: set-permissions
          image: opensuse/leap
          command:
            - /bin/bash
            - -c
            - >
              chown -Rv 25000:25000 /steam &&
              chown -Rv 25000:25000 /steamcmd &&
              chown -Rv 25000:25000 /server-files &&
              chown -Rv 25000:25000 /cluster-shared
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: steam
              mountPath: /steam
            - name: steamcmd
              mountPath: /steamcmd
            - name: ark
              mountPath: /server-files
            - name: cluster
              mountPath: /cluster-shared
      containers:
        - name: ark
          image: {{ .Values.server.image }}
          command: ["/usr/bin/start_server"]
          securityContext:
            runAsUser: 25000  # Game server user ID
            runAsGroup: 25000 # Game server group ID
          env:
            - name: SERVER_MAP
              value: "{{ .Values.server.map }}"
            - name: SERVER_NAME
              value: "{{ .Values.server.name }}"
            - name: SERVER_PASSWORD
              value: "{{ .Values.server.password }}"
            - name: SERVER_ADMIN_PASSWORD
              value: "{{ .Values.server.adminPassword }}"
            - name: ASA_START_PARAMS
              value: '{{ .Values.server.startParams | default "TheIsland_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=50 -clusterid=default -ClusterDirOverride=/home/gameserver/cluster-shared" }}'
            - name: ENABLE_DEBUG
              value: '{{ .Values.server.debug | default "0" }}'
          ports:
            - containerPort: 7777
              protocol: UDP
            - containerPort: 27020
              protocol: TCP
          volumeMounts:
            - name: steam
              mountPath: /home/gameserver/Steam
            - name: ark
              mountPath: /home/gameserver/server-files
            - name: cluster
              mountPath: /home/gameserver/cluster-shared
            - name: steamcmd
              mountPath: /home/gameserver/steamcmd
      volumes:
        - name: ark
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.ark.existingClaim | default (printf "%s-ark" (include "ark-server.fullname" .)) }}
        - name: steamcmd
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.steamcmd.existingClaim | default (printf "%s-steamcmd" (include "ark-server.fullname" .)) }}
        - name: cluster
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.cluster.existingClaim | default (printf "%s-cluster" (include "ark-server.fullname" .)) }}
        - name: steam
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.steam.existingClaim | default (printf "%s-steam" (include "ark-server.fullname" .)) }}

