apiVersion: v1
kind: Service
metadata:
  name: {{ include "ark-server.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.type | eq "LoadBalancer" }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | default "" }}
  {{- end }}
  selector:
    app: {{ include "ark-server.name" . }}
  ports:
    - name: game
      port: {{ .Values.service.gamePort | default 7777 }}
      protocol: UDP
      targetPort: {{ .Values.service.gamePort | default 7777 }}
    - name: peer
      port: {{ .Values.service.peerPort | default 7778 }}
      protocol: UDP
      targetPort: {{ .Values.service.peerPort | default 7778 }}
    - name: query
      port: {{ .Values.service.queryPort | default 27015 }}
      protocol: UDP
      targetPort: {{ .Values.service.queryPort | default 27015 }}
    {{- if gt (int .Values.service.rconPort) 0 }}
    - name: rcon
      port: {{ .Values.service.rconPort | default 27020 }}
      protocol: TCP
      targetPort: {{ .Values.service.rconPort | default 27020 }}
    {{- end }}
