apiVersion: v1
kind: Service
metadata:
  name: {{ include "ark-server.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "ark-server.name" . }}
  ports:
    - name: game1
      port: 7777
      protocol: UDP
      targetPort: 7777
    - name: game2
      port: 7778
      protocol: UDP
      targetPort: 7778
    - name: query
      port: 27015
      protocol: UDP
      targetPort: 27015
