apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-britannia
  namespace: games
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft-java
      version: 22.34.11
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: false
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    global:
      fallbackDefaults:
        # -- Define a storageClassName that will be used for all PVCs
        # Can be overruled per PVC
        storageClass: "truenas-nfs-csi"

    TZ: "America/Los_Angeles"

    resources:
      requests:
        memory: 4Gi
      limits:
        memory: 16Gi

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                - name: OVERRIDE_SERVER_PROPERTIES
                  value: "true"
                - name: VIEW_DISTANCE
                  value: "32"
                - name: MOTD
                  value: "Welcome to Venture Britannia Minecraft!"
                - name: MEMORY
                  value: "16384M"
                # GUI: "FALSE"
                # - name: VERSION
                #   value: "LATEST"
                # - name: TYPE
                #   value: "VANILLA"
                # - name: DIFFICULTY
                #   value: "easy"
                # - name: MAX_PLAYERS
                #   value: "20"
                # - name: MAX_WORLD_SIZE
                #   value: "10000"
                # - name: ALLOW_NETHER
                #   value: "true"
                # - name: ANNOUNCE_PLAYER_ACHIEVEMENTS
                #   value: "true"
                # - name: ENABLE_COMMAND_BLOCK
                #   value: "false"
                # - name: FORCE_GAMEMODE
                #   value: "false"
                # - name: GENERATE_STRUCTURES
                #   value: "true"
                # - name: HARDCORE
                #   value: "false"
                # - name: MAX_BUILD_HEIGHT
                #   value: "256"
                # - name: MAX_TICK_TIME
                #   value: "60000"
                # - name: SPAWN_ANIMALS
                #   value: "true"
                # - name: SPAWN_MONSTERS
                #   value: "true"
                # - name: SPAWN_NPCS
                #   value: "true"
                # - name: MODE
                #   value: "survival"
                # - name: PVP
                #   value: "false"
                # - name: LEVEL_TYPE
                #   value: "DEFAULT"
                # - name: LEVEL
                #   value: "world"
                # - name: ONLINE_MODE
                #   value: "true"
                # - name: RCON_PASSWORD
                #   valueFrom:
                #     secretKeyRef:
                #       name: rcon-secret
                #       key: rcon_password
                # - name: PACKWIZ_URL
                #   value: ""
                # - name: CUSTOM_SERVER
                #   value: ""
                # - name: QUILT_LOADER_VERSION
                #   value: ""
                # - name: QUILT_LAUNCHER
                #   value: ""
                # - name: QUILT_LAUNCHER_URL
                #   value: ""
                # - name: PUFFERFISH_BUILD
                #   value: "lastSuccessfulBuild"
                # - name: FORGEVERSION
                #   value: ""
                # - name: FORGE_INSTALLER
                #   value: ""
                # - name: FORGE_INSTALLER_URL
                #   value: ""
                # - name: FABRIC_LOADER_VERSION
                #   value: ""
                # - name: FABRIC_INSTALLER
                #   value: ""
                # - name: FABRIC_INSTALLER_URL
                #   value: ""
                # - name: SPIGOT_DOWNLOAD_URL
                #   value: ""
                # - name: BUILD_FROM_SOURCE
                #   value: "false"
                # - name: BUKKIT_DOWNLOAD_URL
                #   value: ""
                # - name: PAPERBUILD
                #   value: ""
                # - name: PAPER_DOWNLOAD_URL
                #   value: ""
                # - name: AIRPLANE_BUILD
                #   value: "lastSuccessfulBuild"
                # - name: MAGMA_CHANNEL
                #   value: "stable"
                # - name: MOHIST_BUILD
                #   value: ""
                # - name: CANYON_BUILD
                #   value: ""
                # - name: SPONGEBRANCH
                #   value: "STABLE"
                # - name: SPONGEVERSION
                #   value: ""
                # - name: LIMBO_BUILD
                #   value: "LATEST"
                # - name: LIMBO_SCHEMA_FILENAME
                #   value: "default.schem"
                # - name: CRUCIBLE_RELEASE
                #   value: "latest"
                # - name: FTB_MODPACK_ID
                #   value: ""
                # - name: FTB_MODPACK_VERSION_ID
                #   value: ""
                # - name: CF_SERVER_MOD
                #   value: ""
                # - name: CF_BASE_DIR
                #   value: ""
                # - name: USE_MODPACK_START_SCRIPT
                #   value: "true"
                # - name: FTB_LEGACYJAVAFIXER
                #   value: "false"
                # - name: WHITELIST
                #   value: ""
                # - name: OPS
                #   value: ""
                # - name: ICON
                #   value: ""
                # - name: SEED
                #   value: ""
                # - name: GENERATOR_SETTINGS
                #   value: ""
                # - name: WORLD
                #   value: ""
                # - name: FORCE_REDOWNLOAD
                #   value: "false"
                # - name: USE_FLARE_FLAGS
                #   value: "false"
                # - name: USE_AIKAR_FLAGS
                #   value: "true"
                # - name: USE_SIMD_FLAGS
                #   value: "false"
                # - name: JVM_OPTS
                #   value: "-server nogui" # -Xms512M -Xmx2048M
                # - name: JVM_XX_OPTS
                #   value: "+UseG1GC"
                # - name: CF_API_KEY
                #   value: ""
                # - name: CF_PAGE_URL
                #   value: ""
                # - name: CF_SLUG
                #   value: ""
                # - name: CF_EXCLUDE_INCLUDE_FILE
                #   value: ""
                # - name: CF_EXCLUDE_MODS
                #   value: ""
                # - name: CF_FORCE_INCLUDE_MODS
                #   value: ""
                # - name: CF_FORCE_SYNCHRONIZE
                #   value: ""
                # - name: CF_OVERRIDES_SKIP_EXISTING
                #   value: ""
                # - name: CF_PARALLEL_DOWNLOADS
                #   value: ""
                # - name: CF_SET_LEVEL_FROM
                #   value: ""

    service:
      main:
        annotations:
          mc-router.itzg.me/defaultServer: "true"
          mc-router.itzg.me/externalServerName: "britannia-mc.***REMOVED***"
