apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nextcloud-stage
  namespace: flux-system
spec:
  interval: 10m
  path: apps/nextcloud/nextcloud-stage/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
