apiVersion: v1
kind: Secret
metadata:
    name: sshwifty-secret
    namespace: web-services
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:IjjYw1RH5uYS45kfTxmB8LibNJcC/ly6DJPxT6BWTzo=,iv:745gMRXTb8xBjE/CjhM4qY5JiZNkqUbIvlR4mP5t+vI=,tag:NT4icNxwbypKUj1/+cpRjA==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdDJaRTg3MnByZlRKZDBV
            eGV0NmxhK0xxd3BxWVRDWk9kK1lCVWp6aG5vClpRSVkrd2JPSVhRNERWaXNsK2pH
            WFl6V2VzdkZCblZFY20vYUs0NUNCdDQKLS0tIGVHV01naTNpZkNzODlTTlBPVDYx
            TGc2NE9tbnpOcVVWVXM0dW5hR05TYWcKIAuXBb3c23efhDGmgBfkAyP214kaoVOD
            Qp4rKFGRiRcCpZsxtqDEJFnXLatsSxLCh4RnelMDd4CQ+pUmpom/Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-22T03:53:07Z"
    mac: ENC[AES256_GCM,data:LTDyDFNwdkJ0+glj4AowfR0FTYTgwUr979JpjQHEg7U1t8ivRT5WgxJ19Cmwg+d5WanUquhDx/P9aJxlh7KrOUihhTu7rvL2I/q48DyB7bxR9torOaFO82C5gxJ9HHlwUAUdE9IsU8ahjfvWeCcaaxHBF4rHPlr0pHQkxMbWnqs=,iv:pMaXgZkhmYDdORVHgh0OMKXKi1UHgvCk01vx60NmuYQ=,tag:stvfE7bNVDxkKDvYcpLvGw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
