# This file must be encrypted with SOPS before committing.
# Run: sops --encrypt --in-place apps/finance/ib-gateway/app/secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: ib-gateway-credentials
    namespace: finance
type: Opaque
stringData:
    TWS_USERID: ENC[AES256_GCM,data:j2ECOa9iWbq9,iv:yscXsx6l/6bu2wEHn7sieYvJQ48FC1Pk4skGcQUksVA=,tag:ya1RoBKU11KF2+jBrbh7aA==,type:str]
    TWS_PASSWORD: ENC[AES256_GCM,data:42hl1Uun/do1MInvBrXWpwkbIMs=,iv:W2slya4YmiBdT8XQzbApnkHpZBd2fH/HJDcGw8ogyU4=,tag:BnU6HvK5HDoQCsWxCwPpMA==,type:str]
    TWS_TOTP_KEY: ENC[AES256_GCM,data:/x9Zsj7g4TIT5HkbRwyl+OsJ6uXqdpE6MzGHg4z74co=,iv:St28UH5uxyqWdh6m2zPsktWtoeJ1vsRkB+Y1Ec044y4=,tag:BLx0VtL2hd9RG6rVllU8pQ==,type:str]
    VNC_SERVER_PASSWORD: ENC[AES256_GCM,data:yarEYzHYNL65qV8jZBdl,iv:Li5Ha/8wHhpnUx9uSA52CaBClnL9YVEopZQDesxXPG4=,tag:VSU7wj6qUaZUP8CYHthFMw==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbDZOSHJtaWtqVzRheEFF
            TFUwL1hidnRrUjhtbXlRSnhIVDhzNjlSb1QwCnJGMDdablNrQm1PWU5Wc1ZJa1NX
            WWtWbFFiV2JjVWFlTm1qdVhYK1B3S1UKLS0tIENQaXVjMW0yT3JMYmFoUzJzTUpv
            SFh3R1VFV3haVGNnZ25XY3U0bVNSaTQKgP9ZlbVes026wdKd74J4abyQO/cKL80u
            4qss5/wPNcsg7vAOExjPs0OXIwCUq8+bRPNbeFEU9lhZRqttfz9QGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T20:48:51Z"
    mac: ENC[AES256_GCM,data:fr9pqdO87JB0K48scuFRER6BlAa6PoQBUO+xxM/HpE5WK+7N+njWdZZoQOPoaYhFNEd5hCmGSOdxWSmSkCfZuE8x4V2Ad4dAmJbQUwFmPpa5gdCeCYalJtGkAw/yKJrFGtiVaRCKKzGp56skTHnG3zSwMWxMXOK7x0kxpNLzbFQ=,iv:uEwoHM2btxNBGYIURKFFuyNY+YSZA4kUNSDd331j3gE=,tag:ZTLbBGMR5pYqOp/Cm1JJEw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
