apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: palworld
  namespace: games
spec:
  interval: 5m
  chart:
    spec:
      chart: palworld
      version: 5.3.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: false
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: game-secrets
      valuesKey: BASE_DOMAIN
      targetPath: BASE_DOMAIN
    - kind: ConfigMap
      name: game-secrets
      valuesKey: GAME_PASSWORD
      targetPath: GAME_PASSWORD
    - kind: ConfigMap
      name: game-secrets
      valuesKey: RCON_PASSWORD
      targetPath: RCON_PASSWORD
  values:
    global:
      fallbackDefaults:
        storageClass: "truenas-iscsi-api-csi"

    TZ: "America/Los_Angeles"

    palworld:
      game:
        ServerName: "Venture Pals"
        ServerDescription: "Venture Brothers Dedicated Palworld Server"
        ServerPassword: {{ .Values.GAME_PASSWORD }}
        AdminPassword: {{ .Values.RCON_PASSWORD }}
        bUseAuth: true
        PublicIP: {{ .Values.BASE_DOMAIN }}
        # AllowConnectPlatform: "Steam|Xbox"
      params:
        - -players=32

    service:
      main:
        type: LoadBalancer
