apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apt-cacher-ng
  namespace: mirrors
spec:
  interval: 15m
  chart:
    spec:
      chart: apt-cacher-ng
      version: 10.5.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 25m
  install:
    createNamespace: false
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: mirrors-config
      valuesKey: BASE_DOMAIN
      targetPath: baseDomain
  values:
    fallbackDefaults:
      storageClass: "truenas-nfs-api-csi"
      pvcSize: 10Gi

    TZ: "America/Los_Angeles"

    service:
      main:
        type: LoadBalancer

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: "{{ .Release.Name }}.elite.internal"
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: selfsigned
