apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: bad-employee-cnpg
  namespace: default
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15
  storage:
    size: 1Gi
    # storageClass: standard
  # superuserSecret:
  #   name: bad-employee-cnpg-superuser
  # bootstrap:
  #   initdb:
  #     database: bademployeedb
  #     owner: bademployeeuser
  #     secret:
  #       name: bad-employee-cnpg-app