apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bad-employee
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: bad-employee-bot
      version: ">0.1.3"
      sourceRef:
        kind: HelmRepository
        name: bad-employee-bot-chart
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: false
  valuesFrom:
    - kind: ConfigMap
      name: bad-employee-bot-secrets
      valuesKey: GEMINI_API_KEY
      targetPath: workload.main.podSpec.containers.main.env.GEMINI_API_KEY
    - kind: ConfigMap
      name: bad-employee-bot-secrets
      valuesKey: DISCORD_APP_TOKEN
      targetPath: workload.main.podSpec.containers.main.env.DISCORD_APP_TOKEN
  values:
    # https://github.com/fossum/bad-employee-bot/blob/main/chart/values.yaml
    image:
      pullPolicy: Always

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                BASE_DOMAIN: "bad-employee.fossum.io"
                # GEMINI_API_KEY and DISCORD_APP_TOKEN injected via valuesFrom above
