apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: proxmox
  namespace: flux-system
spec:
  interval: 10m
  path: apps/web-services/proxmox/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
