apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bookstack
  namespace: flux-system
spec:
  interval: 10m
  path: apps/web-services/bookstack/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
