apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valheim
  namespace: games
spec:
  interval: 1h
  chart:
    spec:
      chart: valheim
      version: 12.5.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 1h
  install:
    createNamespace: false
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: game-secrets
      valuesKey: TEMP_PASSWORD
      targetPath: TEMP_PASSWORD
    - kind: ConfigMap
      name: game-secrets
      valuesKey: GAME_PASSWORD
      targetPath: GAME_PASSWORD
  values:
    TZ: "America/Los_Angeles"

    persistence:
      config:
        enabled: true
        # storageClass: "longhorn"
        storageClass: "truenas-iscsi-api-csi"
        mountPath: /config
      backups:
        enabled: true
        storageClass: "truenas-nfs-api-csi"
        mountPath: /backups

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                SERVER_NAME: VentureBro's Valheim
                WORLD_NAME: VentureHeim
                SERVER_PUBLIC: false
                UPDATE_INTERVAL: 10800
                BACKUPS: true
                BACKUPS_INTERVAL: 43200
                BACKUPS_MAX_AGE: 3
                SUPERVISOR_HTTP_USER: ericfoss
                SUPERVISOR_HTTP_PASS: {{ .Values.TEMP_PASSWORD }}
                SERVER_PASS: {{ .Values.GAME_PASSWORD }}
                VALHEIM_PLUS: false
                BEPINEX: true

    service:
      main:
        type: LoadBalancer
