apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valheim
  namespace: games
spec:
  interval: 10m
  timeout: 20m
  chart:
    spec:
      chart: valheim
      version: 12.5.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 1h
  # valuesFrom:
  #   - kind: ConfigMap
  #     name: game-config
  #     valuesKey: ADMIN_LIST_IDS
  #     targetPath: workload.main.podSpec.containers.main.env.ADMINLIST_IDS
  #     optional: false
  #   - kind: ConfigMap
  #     name: game-config
  #     valuesKey: PERMITTED_IDS
  #     targetPath: workload.main.podSpec.containers.main.env.PERMITTEDLIST_IDS
  #     optional: false
  #   - kind: ConfigMap
  #     name: game-config
  #     valuesKey: GAME_PASSWORD
  #     targetPath: workload.main.podSpec.containers.main.env.GAME_PASSWORD
  values:
    TZ: "America/Los_Angeles"

    persistence:
      config:
        storageClass: "longhorn"
        size: 1Gi
      backups:
        enabled: true
        existingClaim: "valheim-backups"

    workload:
      main:
        strategy: Recreate
        podSpec:
          containers:
            main:
              env:
                SERVER_NAME: VentureBro's Valheim
                WORLD_NAME: VentureHeim
                UPDATE_IF_IDLE: true
                BACKUPS: true
                BACKUPS_MAX_AGE: 30 # days
                BACKUPS_CRON: "0 */4 * * *" # every 4 hours
                SUPERVISOR_HTTP: false
                SERVER_PASS: ""
                SERVER_PUBLIC: false
                VALHEIM_PLUS: true
                VPCFG_Server_enabled: true
                VPCFG_Server_enforceMod: false
                VPCFG_Server_disableServerPassword: true
                BEPINEX: false

    service:
      main:
        type: LoadBalancer
