apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valheim
  namespace: games
spec:
  interval: 1h
  chart:
    spec:
      chart: valheim
      version: 12.5.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 1h
  install:
    createNamespace: false
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: game-config
      valuesKey: ADMIN_LIST_IDS
      targetPath: workload.main.podSpec.containers.main.env.ADMINLIST_IDS
    - kind: ConfigMap
      name: game-config
      valuesKey: PERMITTED_IDS
      targetPath: workload.main.podSpec.containers.main.env.PERMITTEDLIST_IDS
    # - kind: ConfigMap
    #   name: game-config
    #   valuesKey: GAME_PASSWORD
    #   targetPath: workload.main.podSpec.containers.main.env.GAME_PASSWORD
  values:
    TZ: "America/Los_Angeles"

    persistence:
      config:
        enabled: true
        storageClass: "longhorn"
        # storageClass: "truenas-iscsi-api-csi"
        mountPath: /config
        size: 1Gi
        existingClaim: "pvc-096b4880-38fc-4cf3-b7e2-b78233a6c758"
      backups:
        enabled: true
        storageClass: "truenas-nfs-api-csi"
        mountPath: /backups
        existingClaim: "pvc-011b2dae-d14f-43cd-a528-6a2c7ed1cc31"

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                SERVER_NAME: VentureBro's Valheim
                WORLD_NAME: VentureHeim
                UPDATE_IF_IDLE: true
                BACKUPS: true
                BACKUPS_MAX_AGE: 30 # days
                BACKUPS_CRON: "0 */4 * * *" # every 4 hours
                SUPERVISOR_HTTP: false
                SERVER_PASS: ""
                SERVER_PUBLIC: false
                VALHEIM_PLUS: true
                VPCFG_Server_enabled: true
                VPCFG_Server_enforceMod: false
                VPCFG_Server_disableServerPassword: true
                BEPINEX: false

    service:
      main:
        type: LoadBalancer
