apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: truenas-iscsi
  namespace: flux-system
spec:
  interval: 10m
  path: apps/storage/truenas-iscsi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      BASE_DOMAIN: thefoss.org
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
