apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-config
    namespace: observability
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:jpFrv2IVmMvf1pYgCJj7Pv6OkHVgcCDtf655lRSSNBjTxVCjGeZlenIXzw7O4MNrGvE8T0sN3phCsqIMJXpfTnVDK+GLE3ugbaipNunJ7w1fEsv8kR4HjrQOBOcz5pNFX/U+fch0DVGDEET2sNQhrssXJsbqbjb8Ymxp+dr9ntGiqYSmgUNBQ2NV4vLuUqBfyfRhL6MDEpt6oMsDBaTsLJAGAsqhYkSVZvLn1f/2AiivceMT9ULx7vQcBLzgpUPlUtObgkDhV9JkvUtEEgnIOUqgYc0tvR1xsYBnWK/YzbIoi1NgR5Bbt3YdlhblOpg4gu0u2wvtVfpGoQLHj4C4YaqV+xnNHxChO5LH3Lhj470o4sHlK+6+Pg70EfxXVVDnb2zKK27eJ+j8Kp8KwsoUwmBErS2j62eBL0nM1Tqj5aZHAyAkEHQ+fqCNETKCNzdzuP7/PEIqhVsQsQV9BeYdJ4UrcKKkaV91EUJ6OznMNHZOAyNu9mvB8wdNPD6SPdoUpkXtbqBd2iemahOf7/ddjO4DQ99M9JUZGII82no=,iv:bPT++L0yFjKjR8Ls/pxXf9DHjbTMENZzQMLIPLvssPU=,tag:psOBpebQoYisvYJW889o6w==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dU54YXAyTmYwdC9LN0NR
            U3hoSXNnRmFjUCtxU3RCSkFXR09GNVltUFE4Cm13QWRlSUtuQnNtZWNQS1hIekhr
            dXdqeVlGYm1rYXZrcUxha0UycVhvU28KLS0tICtGUVd6YXo0ZEROT1crQzJhcEFD
            UzQyVWFvVHlFSE5qVHlqZWlFNU51K0EKuxQcKRswQpV56AE9NbU7PSoPVU6Da9ak
            /MwjEYEUkjU7sXB9UhykK8jShN9SxADKqPrdHV6AdWUgp+qO0H4nbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-21T17:57:12Z"
    mac: ENC[AES256_GCM,data:oFRmzt5L5eOy3c9ijtLXpnX6BalmpPUVZlkktkCq1Mcti/EMC7UccT3cIMa1QPlVpxmBtu2gX8VdvVkyOQuRAGaiknivaDWnNpVQrYyMA4IO85E91/XwLAkLJIAR6IzVlPrMqAOnASEJ/8y89UMIxvZwTZfHkecBuwbbZjZcnn0=,iv:8pzsuLiN3ehd0l9M7i2S/7nbKJ1qdniBiaDJ6MVfN/4=,tag:Y5oYcLTyoA8GaQ99+QwuRg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
