apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-config
    namespace: observability
type: Opaque
stringData:
    alertmanager.yaml: "ENC[AES256_GCM,data:A+OxgDgAgevrLupYk0q2ENtqFET7V0FL0uY3O9awdv30RemycEkZkY9KhVjrRuBZNTjmedzSksHLhJEZY+3WWMFytz/WYv96upSHBUt5ID7IqmrLj3SRSnYXMrc9D+O32wi3hgrxZ2apQknBPen+XOdh/Ts0Vn7IrIMJGWP1/Qy+aMW6O8rfGc+u8RzVsozY4A6WPUvwQYPTzBU5JHOkudcdhRvjRgSkzIU6qXU7W09Nl7tELwrihOqUr0bMkjUjhgWO0ShxW45NmWoVBga5U7G6Nf9I8sFGdkrVjpFBFO9YU762RsbYnM4U/50WfvUkOTXReaqy5Cl67TrBKv22RPrfn+gcCFPqIptjSc/tEWuVwA9xplboEQxMHm3H9hOVYKbuD6TbgRBq+p9BHtbbNO4cs2tR+NZjrSuhJK3QISu3mM3uhBdbIwtmHivA13AqgCBVo54Q/cmxNah+12tP3Ytt6dpee2sq35bjb5MV2pGtnfzCVVwk8BWIHBMBNwIBYZ0BuLiNQ+JrbINnZ2kDrzH7tPpJuDdRz0DBQSjm5mBQfYUq3GSJruqKnMvpx4uLX/YpbM1dKGqip9hZTsAd3ynII7Mzhbg0Tx9lZb+PBJWO6N5T3WRQ0tjFC8eAxkc=,iv:fHdqaVL7vPMdXQdAt9Np1jJ2lIEuTzZsfFljPYJfSVA=,tag:z7aa8CyH52givDz90rRWHQ==,type:str]"
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYzErOFgySnpNbklKUzZr
            UTJDVlZ0c1RDdVFkR09waTZmWEJlNUtheFRvCjlienZ6ZGdiMVhONW5vcVp2M1I2
            U3FzYWFyVkltS0hsRFhKbUMwUHhDdFEKLS0tIEF5clV3SVZQZFFSMDd3RWZGSmtj
            c3E4Y2FlU0hzemZJeis4NGpvTjlTZDQKHH59QbfeMeByZL8zGhnZeS1ZWjGXT9tw
            PFn3VOk1UVWFfHZg6seGxcIfNYmAxld6d6cdOJKueANQiMcq0MyWbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T01:00:31Z"
    mac: "ENC[AES256_GCM,data:9YSaXawWyjl5cmqIcCXsYZ0XVcR2cHDay874Ox+6pmUg0QO8hrD4WmAz/IunmGb7fQp35VBP0jWGcRdHTbnxG5hUd9R7TPT285zMVXU6T0M8yb8/Ptma2t2neazqP1iTGyCcplwsKCCllkQ9yS/Z5e3Gc/g813jBHsjXe2Z40WQ=,iv:FC7+RTW1uOK3h0C/dovEmPsBggVl7KuAU1K6MbeTgv4=,tag:42rDHBR9RXkZCFFMaMwhyg==,type:str]"
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
