apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cert-manager
  namespace: observability
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - infrastructure
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - cert-manager
          - cainjector
          - webhook
      - key: app.kubernetes.io/instance
        operator: In
        values:
          - cert-manager
      - key: app.kubernetes.io/component
        operator: In
        values:
          - cainjector
          - controller
          - webhook
  podMetricsEndpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
