apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: observability
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:ta3IEyE=,iv:cTpwMDA0pbJPnTY2SFzvzGic3Vsd6clR/e8W9CpeARo=,tag:r25ZlbogEYXbqM9LotsuEA==,type:str]
    admin-password: ENC[AES256_GCM,data:EOqsw+0h0cszMxcWwzT6IVAI/DiQ/ZliZr0=,iv:tb4IB2dokuwxt0gTPlzqwWTX5D3oHpdOoENhSIoe5OE=,tag:BDYJKo8F2C2vHDBACgvFAw==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVzRTbHRyR0REUEM0aWFV
            S0YwTm80eU5OdlVTcnhiVExnZDVOci9vYkUwCmN1a1ZDVXlqVk9ydGlhT1ZId1N4
            TGN5UzJkalhKaTVFblAxQ0tjSXBqdmcKLS0tIGZxelRVelk0K1pZaHd1TnpBTmRO
            bXJhZXpoWW1hdXhJeHVwdEhJeEVFQ0UKIsZBjEmq7yM4tgN6luTxYnvN47ZDp7J2
            yB/NpCJM3R4Q148JNe1l2ck16FbYVapWL8iRnYj1BUAT2Ra1ftj6iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T01:00:31Z"
    mac: ENC[AES256_GCM,data:5HsFk7CrVI/tctcVR/sNsmiP4Pk7nMlh8u2pcbnbJug7ktSwIVbQnRZNeNayWllazGjXbunc+gQflb6N131OgkpvS0lsP7rDdP/e2PNghGv915fyhlCZFMf+2M0v66GUzNsgK6uqkIijjtuBYSH4yMoamxfq72rSXI5KyteN5XY=,iv:j9u4/sW+5JzEr62lsXsumGEHRdWv2pOJTSUqTCIUTWE=,tag:ga1pijiBR3pP2yhOmx4lrA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
