apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: garage-fridge-cnpg-main
  namespace: home
spec:
  instances: 1 # Number of PostgreSQL instances (1 for single instance, 3 for HA)

  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: garage-fridge-lb
            spec:
              type: LoadBalancer

  # PostgreSQL major version is usually determined by the operator's default
  # or can be specified with `imageName` or `imageTag` if you need a specific version.
  # Refer to the CNPG documentation for how to specify PostgreSQL versions if needed.
  # e.g., imageName: "ghcr.io/cloudnative-pg/postgresql:15.6" (check for current supported images)
  # imageCatalogRef:
  #   apiGroup: postgresql.cnpg.io
  #   kind: ImageCatalog
  #   name: postgresql
  #   major: 16
  # imageName: "ghcr.io/cloudnative-pg/postgresql:16.8"

  # Initial database and owner setup during bootstrap
  bootstrap:
    initdb:
      database: garage-fridge # This will be the name of the database created for GitLab
      owner: garage-fridge                 # This will create a PostgreSQL user named 'gitlab'
                                    # and make it the owner of the 'gitlabhq_production' database.
      # The password for this 'gitlab' user will be auto-generated by CNPG
      # and stored in a Kubernetes Secret named '<cluster-name>-app'
      # (e.g., 'gitlab-pg-cluster-app' in this case).
      # You can also specify encoding, locale, etc. here if needed.

  storage:
    size: "10Gi" # Adjust the storage size based on your GitLab needs.
    storageClass: "longhorn" # You mentioned using Longhorn.

  # Optional: PostgreSQL Parameters (uncomment and adjust as needed)
  # postgresql:
  #   parameters:
  #     max_connections: "300"
  #     shared_buffers: "1GB"

  # Optional: Monitoring (if you have Prometheus Operator installed)
  # monitoring:
  #   enablePodMonitor: true

  # Optional but Highly Recommended: Backup Configuration
  # (This is a basic example; configure Barman object store for proper backups)
  # backup:
  #   target: primary # Take backups from the primary instance
  #   barmanObjectStore:
  #     destinationPath: "s3://your-s3-backup-bucket/gitlab-db/" # Your S3 bucket and path
  #     s3Credentials:
  #       accessKeyId:
  #         name: gitlab-db-backup-s3-creds # Name of a K8s Secret holding AWS_ACCESS_KEY_ID
  #         key: aws_access_key_id
  #       secretAccessKey:
  #         name: gitlab-db-backup-s3-creds # Name of a K8s Secret holding AWS_SECRET_ACCESS_KEY
  #     # endpointURL: "https://s3.your-region.amazonaws.com" # if not using AWS default S3 endpoint
  #     # WAL settings also go here for Point-in-Time Recovery (PITR)
  #   retentionPolicy: "14d" # Keep backups for 14 days
  #   schedule: "0 0 2 * * *" # Daily at 2 AM UTC
