apiVersion: source.toolkit.fluxcd.io/v1beta2 # Use the API version for HelmRepository in your Flux version
kind: HelmRepository
metadata:
  name: gitlab
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.gitlab.io/