apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ark-fjordur
  namespace: games
spec:
  interval: 5m
  timeout: 30m
  chart:
    spec:
      chart: charts/stable/arksurvivalascended
      version: 0.1.1
      sourceRef:
        kind: GitRepository
        name: fosscharts
        namespace: flux-system
      interval: 5m
  values:
    TZ: "America/Los_Angeles"
    service:
      main:
        type: LoadBalancer
