apiVersion: v1
kind: Secret
metadata:
    name: thefoss-le-prod-clusterissuer-secret
    # Or whatever namespace your ClusterIssuer is in
    namespace: infrastructure
type: Opaque
stringData:
    cf-api-token: ENC[AES256_GCM,data:xsq6l525gafEqS/OwMXaVbNfZaBGTU8TOLk8MUjGmzjcbqD2hgCkmA==,iv:8c1JvmQnYA9NzH72y69UIOkwqS0Rq9qz+Tu2AcSrCWA=,tag:ZYfE3MI9E8Q0BtqMgwzp6A==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTWtrZEJFVXphRWpDVXV1
            TTFSMnRweVhVRVpjTm91ZzZzZ0p4L3JCSTNvClZ2eC92UE93Z3ZENGZqemhEeTRv
            dzY0UjdWMm5zWUFqaTl0VWpxaTFVTHMKLS0tIFVPaGp2RVh3MjJBMVRWMDhYdURx
            UlYvMkFKTmFUbjN6VENsaXVORkkwdXcKm5MQN7M6uV/3C3NTp29btOsHABsSubGh
            PWk5VT/q3mmGZGIl6ZyqGzrmhCMhKb1kOIcttWQbbv4GkY1sQBRAVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-03T15:03:42Z"
    mac: ENC[AES256_GCM,data:HoCq9STpG+dTwse8yQ/IaiiQLRwcG8zxwqvtL2CNZYgy1Or3eK31/cIIK/T6LPjPk0UnUdr9hXiLEJKPFkKvds9rt9ahq+kaVOaG2GN/fjDhzxVEGiMX9Oho1Xog0IpzFrUJdzTVohCsSkXMZb+yGahhwaU6mo+rYvTX+fKSxFo=,iv:L1jWzgFBi8m+Lbcg80Bd4hQstbl7MIVXTRrSUXc0TSk=,tag:0qCLD32hoo9T6BTqN6himw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
