apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: infrastructure
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: 1.18.2
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 5m
  values:
    crds:
      enabled: true
    dns01RecursiveNameservers: "1.1.1.1:53,1.0.0.1:53"
    dns01RecursiveNameserversOnly: false
    enableCertificateOwnerRef: true
