apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: le-prod
  namespace: infrastructure
spec:
  interval: 5m
  chart:
    spec:
      chart: clusterissuer
      version: 9.6.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: false
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    clusterIssuer:
      ACME:
        - name: thefoss-le-prod
          # Used for both logging in to the DNS provider AND ACME registration
          email: "${DOMAIN_0_EMAIL}"
          server: 'https://acme-v02.api.letsencrypt.org/directory'
          type: "cloudflare"
          # Obtained using instructions above
          cfapitoken: "${DOMAIN_0_CLOUDFLARE_TOKEN}"