apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - actual/ks.yaml
  # - bookstack/ks.yaml
  # - chrome/ks.yaml
  # - firefox/ks.yaml
  - grafana.secret.yaml
  - grafana/ks.yaml
  # - home-assistant/ks.yaml
  - homepage/ks.yaml
  - portainer/ks.yaml
  - sshwifty/ks.yaml
  # - web-services.flux.yaml
  - web-services.secret.yaml
  - vpn/ks.yaml
