apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: web-services
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/web-services
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
    namespace: flux-system
  targetNamespace: web-services
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
        optional: false
