apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: jellyfin
      version: 21.1.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 25m
  install:
    createNamespace: false
  valuesFrom:
    - kind: ConfigMap
      name: media-config
      valuesKey: BASE_DOMAIN
      targetPath: baseDomain
  values:
    # https://truecharts.org/charts/stable/jellyfin/

    persistence:
      shared:
        enabled: true
        type: pvc
        existingClaim: dvr-nfs-pvc
        mountPath: /shared

    service:
      main:
        type: LoadBalancer

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: "{{ .Release.Name }}.elite.internal"
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: selfsigned
