server:
  name: YourServerName
  password: ChangeMe1
  adminPassword: ChangeMe2
  map: TheIsland_WP
  image: mschnitzer/asa-linux-server:latest
  clusterID: default
  debug: false
  maxPlayers: 50
  startParams: ""  # Optional, overrides entire start command.
  mods: []  # List of mod IDs to load, e.g., [123456789, 987654321]

service:
  type: LoadBalancer  # or LoadBalancer, ClusterIP, etc.
  loadBalancerIP: ""  # Only for LoadBalancer type
  gamePort: 7777
  peerPort: 7778
  queryPort: 27015
  rconPort: 0

persistence:
  ark:
    size: 50Gi
    storageClassName: ""
    existingClaim: ""
  cluster:
    size: 5Gi
    storageClassName: ""
    existingClaim: ""
  steam:
    size: 2Gi
    storageClassName: ""
    existingClaim: ""
  steamcmd:
    size: 5Gi
    storageClassName: ""
    existingClaim: ""
