server:
  name: YourServerName
  password: ChangeMe1
  adminPassword: ChangeMe2
  map: TheIsland_WP
  image: mschnitzer/asa-linux-server:latest

persistence:
  ark:
    size: 50Gi
    storageClassName: ""
    existingClaim: ""
  cluster:
    size: 5Gi
    storageClassName: ""
    existingClaim: ""
  steam:
    size: 2Gi
    storageClassName: ""
    existingClaim: ""
  steamcmd:
    size: 5Gi
    storageClassName: ""
    existingClaim: ""

service:
  type: NodePort  # or LoadBalancer
