apiVersion: v1
kind: Secret
metadata:
    name: gitlab-cnpg-s3-backup-creds
    namespace: gitlab
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:AtdLLbDPIpy389rUn/R1bL66u+g=,iv:U+jMsO7ALhXS3k/XVKmg1aUa/aXazEP02uPlx841iQw=,tag:oyLSf7jDrbROIlHduLBoHQ==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:hYa9md4UtSkIZqoykkxSOR6saMrbH83MHwl0G6W+ZZwIjiUsQSwxnw==,iv:ntwnzpq0+/MozkQaSOfBr6vJM1JblPLhSJtRY1VEFp0=,tag:VKkH67gE4uqjkZrRDxZs4A==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxN2E5bS9tVVlqVElPRHQ1
            QkRBdUxBb3hKbndPditQY1RyZ0dha1BGR3pjCkZaa3BFa3FFNXM1RXJJOUpNbjg2
            Sm5sT0wyUHlPZjhoMlpwS1lqRkVVRUUKLS0tIGFlUXMva09meC9yaWRpYUFEVTR5
            eFVLaGs4NzAzUDQvcGZsbWhkRm00RUUK1ZGupqA8fPjZz+saDRFIt+d2asSWvEBc
            UEYtWG4izw8IIQ5ZfjSbJeCh1/gPpBcclvH3Y/UE/m0qsQGKlFk7ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T21:26:44Z"
    mac: ENC[AES256_GCM,data:6QhdNBHO7tjQOjpjNQpyHc6t7topw0DR/dm6mUQEfaU9Kp0QRzu80d8OunF9tKD/dGc3Ru2LPPB12BW5SWkXgv6xwFh0kVJvtzlGRoe++A4SYVc5N8JGoQoLfpQhWng+8wVnCu5fRd+3If9WaM9nTCWzddF0kDjSbP9ImOR1Gp8=,iv:M2NNV4CceQj8+4dbA0qTMcfHki66Mw1Me3rPmomv66g=,tag:2SoOmjicM99ezakzXLj7Eg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
