apiVersion: v1
kind: Secret
metadata:
    name: gitlab-registry-storage-driver
    namespace: gitlab
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Fiz3izAF2oNj23Yk/l/aEjTkYnDNoByXub8rARglXZIYNppw1KAPK2eTwag9yzyWo7xVFdRt8dvO6egSSdNqMiDK2REoe6rJs3/YUVVWa7M=,iv:SMgaaQGB65a56pPCI0LwEq8qJrJVbiNOblzfO1JQMn0=,tag:EWk3ckg1Pnt1zMm+QsWHjQ==,type:comment]
    #ENC[AES256_GCM,data:B13ZXiuyHkY/N9punc3/auUY3m41xiw/VDnXp+J52j9KBLRUwuFRit6HvXY/yAI7UUlYm4U+qabVKzzgwoR8WrQLvxaWay4/AbY7vZE=,iv:X9G+hKuIbatR9JLntarmcVZ4I0chymYOAhW3XedFViQ=,tag:ZRUqMLs/9Hj/5ixhVORiCg==,type:comment]
    #ENC[AES256_GCM,data:QrNi3Feq8xRQQtr5Ue0XN7NhdS6fLjcEEEeh+lEy7all4buPI/6enCap10wNmcRvx3W70q+mX9MXQw==,iv:NgBSzREsByW/Ku1cOk/saCnGjZ89SfUlNW452Ukdy34=,tag:3v9H8Z0KdhLsM7oLdiykDw==,type:comment]
    config: ENC[AES256_GCM,data:WCygO4zib5j924L/6+w928KFQITP2GZC77+T5dOgi0MbNUrTt6V7HV6QYMw43E7syktDeus26w8D8SM7uMxLPQ0WJoNmJRC7bbXN+X3brv955+H26wu6ntB4bBr6/uwiIfHCn880XRtWNnEuJlblwkvigesstVe07+7UDvkqFLOIx9YVPYgrCVF5se/GaErGSI6Hko5QRbhnUMx70A7SOYf/HTlEAcDrZhfhXM08S824wotO4/bTLQ/MQ+j8kI/NMUx1nsTqVNoCREj90mLwk+qyAnK764/eMioKKzkUqSrqITCNyl+zrtadtCW6BirXn/JpQuOJG00itUAVS8RelQGmKGQExXiHruNEJuLdsduWOXGlJXC993vP/aRU3m5E,iv:tlHWwmB3vW/0u2J6LoU+SmtY9k98Hsm1FZTcnwtE7Kw=,tag:8WDjzovPe4H3lZuqI3aUjQ==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURGgxOHY3SFVEME9jRXd4
            ek9YL1U5WGFPaE9nZUttNllKNWluRlJ1S3k0ClBoNzZ0Tm96TlZTOWFXSXFiVytK
            TFBxaE5sbTdhOHV4NmNnVHgrM3Y3QVEKLS0tIHlXeEFPMWJITVZ0RDdPTGkvYTNo
            L0RhSTlSd2puRlhLbVVMb1haY1ZaN2sKsrloHXN7Ml8p1BqstiAKC7bkF93WUoxe
            z81wyOoFNEJrZu2p7+SMlHtSqIWHffjjezWyx2qG8rSJbfxRu5Bgzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T17:41:08Z"
    mac: ENC[AES256_GCM,data:jz3dUkbWT8zW3zEmwXFjzCcCWkiO3xeFsJgfwaBBPG3D+jsaV7odVoGZszHr7T4QUlulDE3yRrTH95UDwUCKL3gGm3Ywe5Q6sgtvz08q575kcc/KIeyVEwsFYtR8HEy4Yn6ZzLnXNqLXKnSS7b2lPA9GIDTlSpFLaste+VoWQyc=,iv:Abx9X+nfIh17tH5wYFnn/KZKP8xGhcoU1WVp4d3dLa0=,tag:rDU4Ct5FcIBSJe/W6zpvBQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
