apiVersion: v1
kind: Secret
metadata:
    name: gitlab-s3-configuration
    namespace: gitlab
type: Opaque
stringData:
    connection: ENC[AES256_GCM,data:Tqz5y3pI3O2WRyFT+K+Q/2gyl15LPLkQwK6Us6N858U9vlOmtdNAJLKvOPkLRhRv1mQ/nhSlCrwYTScTDt76kpt3ska90LLS+wJp/rdg5/WpKPQ0CWIw6M/cxM1mmszliz4lgxngWE45pjWSS/n1H/97oR1xUlhkBSXDKZeue3XpN6h4734u5G7TSYmyejqsH2r0yuR1Bo1cuIedrzg9LWN9RjT2vsJ9+D02TFu1mmF7M3xJu3DcgcB3exN307EyjGqUqVmXgoVJpu+GYAsnIs/1U3+RFAwIRaTZ0zRtxz1GaWEUGlLpNVq/lVBdsUPNQ0DvvNKxhRuz2TbeWsEKj1FpBXc7SwcuQNwozNbDxG7YPlpnDe0BmaD360QVnxGblS1zmOHHJSC/+f6iS9i+NHtqVfEFIOK9KEatL74e5/OV4O0JvN/ZZLTOZHPdc9Wf4IFdT35hMjM7iFC5ET66byBH/Yq+OcUqagz0sXpd8Cm0Zisl9MbVlV5gEk8ALY2LtgbX9quh1nlofs2kbu50hJ0CpOXJ2y864ml9+HsUa5G1ouegad4YqohoILVMLyihyjVYvyVHw1f3Mh+Ht4M+OGWF9xbkLJXsy/0hW9n80WLni4+FrHXIIHPKWuLYQtl0a7H7t39i6+OT,iv:BwCpAizh/ZBhIBocAEjt+dPWaYShuUrlM3w7+T+mn5k=,tag:s0HkgBQhrQ7dyBdtWbLXcg==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaa2RnMFJ1cGlVRjVLTkxQ
            ZFozRDhkMi9aMmlJMExSYnp5UnM2NWVXekJrCjBrTEpCUFhPOG5Qc1ZXMzcvTHpR
            UzRPWWF4WVV5UllzZlBHcm5UalF5bUkKLS0tIFI2OGszZFNZOWtvUlBlWFhBSFhr
            dmxpVVhuV1hleHhuSFRuOG4rWXNHOTAKl+VT16oHsbvliQRi7GuA4Ez5y48If+Kx
            Ek/yLaN0arvFeUBlnozasJP7sY7/OmZ3fi0n9RdH11KDxyCXjcuDfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-02T19:21:03Z"
    mac: ENC[AES256_GCM,data:niL2A9HjugdlX7HXqiIJsltF/ttriOB/lF7G+2W1jDUuSUl/h4cHb0vvYyD7kQu9AAx468CfT6xjbhHg9/wZqbw7U0F3fz0oi4UiMs1McQJPDXufRw2yH379xgmimrt88azybQRpiz/blBcFN1dzsHflPQ8Y2ehZiiwRhUhkJ60=,iv:ZvC7MCrYnnsjCHaUk81HibK/b0/KZ9T2fmPhvuntxzc=,tag:8RnaY75YD9lrCYvoiJ9K0Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
