apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller # This will apply to kustomize-controller
  namespace: flux-system
spec:
  template:
    spec:
      volumes:
        - name: sops-age-keys
          secret:
            secretName: sops-age # Your Kubernetes secret with age.key
            items:
              - key: age.key # The key within the sops-age secret
                path: keys.txt # Mount it as keys.txt in the volume
      containers:
        - name: manager
          volumeMounts:
            - name: sops-age-keys
              mountPath: /etc/sops/age # Mount the volume here
          env:
            - name: SOPS_AGE_KEY_FILE
              value: /etc/sops/age/keys.txt # Tell SOPS where to find the key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller # This will apply to helm-controller
  namespace: flux-system
spec:
  template:
    spec:
      volumes:
        - name: sops-age-keys
          secret:
            secretName: sops-age
            items:
              - key: age.key
                path: keys.txt
      containers:
        - name: manager
          volumeMounts:
            - name: sops-age-keys
              mountPath: /etc/sops/age
          env:
            - name: SOPS_AGE_KEY_FILE
              value: /etc/sops/age/keys.txt
