apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: plex
      version: ^21.0.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 25m
  install:
    createNamespace: false
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: media-config
      valuesKey: BASE_DOMAIN
      targetPath: baseDomain
    - kind: ConfigMap
      name: media-config
      valuesKey: LOCAL_IP
      targetPath: localIP
  values:
    persistence:
      config:
        enabled: true
        size: 5Gi
        storageClass: "longhorn"
      media:
        enabled: true
        type: nfs
        path: /mnt/local-raid/no-backup/dvr
        mountPath: /media
        server: "truenas.{{ .Values.baseDomain }}"

    resources:
      limits:
        gpu.intel.com/i915: 1

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                # User Defined
                ALLOWED_NETWORKS: "192.168.0.0/16"
                ADVERTISE_IP: "https://{{ .Release.Name }}.{{ .Values.baseDomain }}/,http://{{ .Values.localIP }}:32400/"

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "{{ .Values.localIP }}"

    plex:
      additionalAdvertiseURL: "https://{{ .Release.Name }}.{{ .Values.baseDomain }}/,http://{{ .Values.localIP }}:32400/"
      requireHTTPS: false
      disableGDM: true

    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
          nginx.org/websocket-services: plex
        hosts:
          - host: "{{ .Release.Name }}.{{ .Values.baseDomain }}"
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: thefoss-le-prod
          homepage:
            enabled: true
            group: "Media"
