apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: plex
      version: 19.6.13
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 25m
  install:
    createNamespace: false
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    persistence:
      config:
        enabled: true
        size: 5Gi
        storageClass: "longhorn"
      media:
        enabled: true
        type: nfs
        path: /mnt/local-raid/no-backup/dvr
        mountPath: /media
        server: "truenas.${BASE_DOMAIN}"

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                # User Defined
                ALLOWED_NETWORKS: "172.16.0.0/12,10.0.0.0/8,192.168.0.0/16"

    service:
      main:
        type: LoadBalancer

    plex:
      additionalAdvertiseURL: "https://{{ .Release.Name }}.${BASE_DOMAIN}/"
      # requireHTTPS: true
      # disableGDM: false

    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: "{{ .Release.Name }}.${BASE_DOMAIN}"
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: thefoss-le-stage
          homepage:
            enabled: true
            group: "Media"
