apiVersion: v1
kind: Secret
metadata:
    name: development-workspace-secrets
    namespace: development
type: Opaque
stringData:
    TAILSCALE_AUTH_KEY: ENC[AES256_GCM,data:gVv5y2LO8BQ5UA==,iv:RVJe6hUWdZn2OorfJcBL4oJOHdOPDxp2FNT3iX736HI=,tag:mnSm+7yGz9U9hlIUZB24Ww==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeEdGd25Fejg4ZVRGYnZU
            WjdsdWtDVFNRbDFha1pRTEJFZE5sVk1rTEh3CmtrQlFGRWl5OHRqVHhrK1BySElt
            Ykh3TzVPRitzbXJPeFdGeUhYTFltcU0KLS0tIFJMMlQ1ajQzazVwWnJCcW9HTTR5
            aUpxVzJZeEsrLzNVazAzaDJBYUc0Mm8K9XM0P+/gUthtC+VNqwtLfC8WHSN95Y/m
            fmWAeEZoDCk8nlkAOaJ1RPLwKfi8djrLgE9FUIJpBzuQLspyyeqXPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T15:20:49Z"
    mac: ENC[AES256_GCM,data:YRhbj8xewIZagZ0soN+QrbgyLN2UBtUmWpJrTvTi1QCM90Od7nDxaUdDvftFb3NMr3qjDHNkxJ9F0tcLnGxikhHBnxwMyngPdJR5LZo+Z2LLc3Y2DVxCd1wQotdxbF8HSoELZmQRfO9t5+Sn2uHN+r7MkNx5xSVrllPOMFL+yRA=,iv:fbYYWGs1V9iv3wRMyx6A0AIxZubXjAVe1LKbPZuuHQk=,tag:T8yvJv+Bq6ujThLseIcnTA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
