apiVersion: v1
kind: Secret
metadata:
    name: development-workspace-secrets
    namespace: development
type: Opaque
stringData:
    TAILSCALE_AUTH_KEY: ENC[AES256_GCM,data:XQch82qZf0RLWT4EsfHFKcNi7Y5COD/S1wSGwZvRHogTEKgGnU7P8In/m4e5m8LIDQd3mzlxq+MZqoQQXw==,iv:rvpuevDncABXefHLMoiCElnm4Do1XqiiRsPD+bBlJko=,tag:1X1Y6HeM2bPOu/f7gSpOMg==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQkZ5SFlsQ0VpbGYvWnA4
            S0JmYWU1UGZxZHIvcmVhWUJxTitOSjZQalVRClpOVUZOVFQzVmhCbjh2MnFzcGpC
            QkowZzhnRDZ3YUp0a2FBUU9yWlh6VVUKLS0tIEtMaFhuOE9CYTZNaEN1dVVpQlpN
            TkhicmwzblVsNXc5SFlmeG4rRHdOV28KIxc3BkxNtSc0E/auciGbmSZZdmoeOUE4
            9GsiXQFN5fjCXXdXwhWPZWA9pl2kiwVnsBLksdhNQo3pHyStVZ6ydg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T15:42:57Z"
    mac: ENC[AES256_GCM,data:7ckMMXmxd7vZ0SXYiKOceV1K6JqD8OJgK3a7XVBW7mlG8DbNB7IiZJfAz/wFM5nYatYFMNFdTCt5nyZNSZVlY1fTkWNMCotxfUv1uy7mQnPBUbqKTsmpQ1zCgjLsOize/fkU6kySyvUrQjdOEfoNfF0mkbxm2pHNJpFR0zi+0R8=,iv:cy7ZZIA83GkgA+HqqkuTEqsfaOvXvS+xzE30aM+2JD8=,tag:NOPlboFY3v2qN3USxZR0NQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
