apiVersion: v1
kind: Secret
metadata:
    name: development-workspace-secrets
    namespace: development
type: Opaque
stringData:
    TAILSCALE_AUTH_KEY: ENC[AES256_GCM,data:/6SuDnb4PK1e6ix/ydaZuLjYl+Bkzy04PsPJNX6HY6znqeYS3qM3QK3ixAk/L5XKTaVVpllJzejUT/tkbQ==,iv:H/TTQn6cwygtLDOoB2Hlw+2oLKDCW+I/Sa1XkpYiaNI=,tag:pxwxkrYXl5B7dRIAjLbo/g==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UUQrdVo1Vml0TTlQcDdv
            TURVakRrdWV4UklxUFBaSjllQkNjVTlObTBRCjFkUFhkdWNrTVpnZWpwRnM5VC9k
            MWlxdHkxYUx4VStzakZVNmFDQ0dqbDQKLS0tIFRnMVkyZjN4UVh2MmNWc21GOFo2
            ZCtIc1BCdjYxd3FIcG1xWjlQc1lGd0UK1ZOLLx1GNEM7OPVovLScKYyHBrR7eMZg
            OougNUN2LU3iBwMaidXCiPuz+vTOwmaynV/TdHyMyqCbAbrjzRcLEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T14:36:35Z"
    mac: ENC[AES256_GCM,data:yC3cuuz3IaM93Ky8P2347Ilv0I/yoSJ3ojPS7bgliZTj0ROk11xmknc2v2VFB05NdVS3IosDP8380G6quE3jmo4+2pKv032oXH6Ivj/gduXir9cqwMiCdnYJSYmtnUbzqJNIPHh68Zwptp22QH2DNES+Y/8NakAy3268WWSi/+Q=,iv:vl2EYe91AeTd2d3a0stQTwexJD+4WbZWv/y85e0ml7o=,tag:9NNozwthOoXjy2OvlDpisA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
