apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-storage
  namespace: development
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs-api-csi
  resources:
    requests:
      storage: 100Gi
