apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-stage-db-credentials
    namespace: nextcloud
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:AOkgy0qiW5s=,iv:sTt91e8F92AaQhVyacwsFnVXp5lgowaV+s3+csbjEs0=,tag:hNyV3GQ12veYB7w5CJHTUQ==,type:str]
    password: ENC[AES256_GCM,data:h5t3fCJsEchdx+0hXMj+6ofR+yMo6wGOC3UayTIiPz2PjGjpNS3TPBquPTQ8L+a7Lw3uEtzJQjAacZqoMCmfow==,iv:1v72MXZ+eoDFiWqovj1IDh/OLhmlfXZYJ7ysrEjPaMw=,tag:+VOSC2qWU2DplPWsiqs2Yw==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOVBHMGxyTEtTM3J0Umo5
            SmtJbENJVDBmckhlZzZIT0h6bjQwL0hvTVZrCjJRZ21kcHVuU1JrdWRya3k0Wnc5
            VjEySWdPYWVXL2JtRlNkL21jcXo0OEUKLS0tIFovRDFtQkVyU0RNZDRQZ2wzdk82
            Mm92MHZZRHNTbUU0T3pxUThBM1ZDbGcKZpIvFt+ytMU0M2w+WbmpmEopEa7saYxb
            fStPUPi6JWKgO991mnALRotgc+w9xsOmMcizdpw9D6qV1XvrpfW9Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T05:32:27Z"
    mac: ENC[AES256_GCM,data:UwFGE7hUV7Bn4J/RhumbTznnnASoTMLOhnieGWgJHij6NYHdeVBsAesslj45K3In1shA4dAjFUfabTQfuNctsmTh3EErIhdanv2h6RsASTKEzVv8kuBVfCutpJKzcl8koIFMfkvA+j2rTd1TKE3fR+oUez+BNG4AhOqIDI+MqT4=,iv:iGI+WO9WLy/Ajqd8R3jbPHsNRJ8QZAPeGO9kLQ6HTbU=,tag:SrG4pQXZkWrINcbZzxCc4g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
