apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud-stage
  namespace: nextcloud
spec:
  interval: 30m
  timeout: 20m
  chart:
    spec:
      chart: nextcloud
      version: ^6.0.0
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      interval: 60m
  install:
    createNamespace: false
    timeout: 45m
  upgrade:
    timeout: 45m
  values:
    # https://github.com/nextcloud/helm/tree/main/charts/nextcloud

    ingress:
      enabled: true
      className: external
      annotations:
        cert-manager.io/cluster-issuer: thefoss-le-prod
        nginx.ingress.kubernetes.io/proxy-body-size: "10G"
      tls:
        - secretName: nextcloud-stage-tls
          hosts:
            - cloud-stage.thefoss.org

    nextcloud:
      host: cloud-stage.thefoss.org
      existingSecret:
        enabled: true
        secretName: nextcloud-staging
        usernameKey: initialAdminUser
        passwordKey: initialAdminPassword
        smtpUsernameKey: smtp-username
        smtpPasswordKey: smtp-password
        smtpHostKey: smtp-host

      mail:
        enabled: true
        fromAddress: fossum.eric
        domain: gmail.com
        smtp:
          host: smtp.gmail.com
          secure: ssl
          port: 465
          authtype: LOGIN

    # Disable built-in Redis for now (can enable later)
    redis:
      enabled: false

    externalRedis:
      enabled: true
      host: redis.infrastructure.svc.cluster.local
      existingSecret:
        enabled: true
        secretName: infrastructure-redis-credentials
        passwordKey: password

    # Use existing PostgreSQL database
    internalDatabase:
      enabled: false

    externalDatabase:
      enabled: true
      type: postgresql
      host: nextcloud2-cnpg-main
      database: app
      user: postgres
      existingSecret:
        enabled: true
        secretName: nextcloud2-cnpg-main-app
        usernameKey: username
        passwordKey: password

    # Increase startup time for initialization and migration
    livenessProbe:
      enabled: true
      initialDelaySeconds: 300
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 30
      successThreshold: 1

    readinessProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 60
      successThreshold: 1

    startupProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 360
      successThreshold: 1

    persistence:
      # Main persistence for /var/www/html (Nextcloud app files)
      enabled: true
      accessMode: ReadWriteOnce
      storageClass: longhorn

      nextcloudData:
        enabled: true
        existingClaim: nextcloud-persistent-data
        accessMode: ReadWriteMany


