apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: web-services
spec:
  chart:
    spec:
      chart: home-assistant
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      version: 27.4.4
  interval: 1m0s
  timeout: 15m0s
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: "{{ .Release.Name }}.${BASE_DOMAIN}"
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: thefoss-le-prod
          homepage:
            enabled: true
            group: "Services"
    homeassistant:
      trusted_proxies:
        # Trust the Kubernetes Pod Network CIDR
        - "10.42.0.0/16"
        # Trust the Kubernetes Service Network CIDR
        - "10.43.0.0/16"
