apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bookstack
  namespace: web-services
spec:
  chart:
    spec:
      chart: bookstack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      version: 16.1.1
  interval: 1m0s
  timeout: 15m0s
  valuesFrom:
    - kind: ConfigMap
      name: web-config
      valuesKey: BASE_DOMAIN
      targetPath: BASE_DOMAIN
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: "{{ .Release.Name }}.${BASE_DOMAIN}"
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: thefoss-le-prod
          homepage:
            enabled: true
            group: "Services"
    workload:
      main:
        strategy: Recreate
        podSpec:
          containers:
            main:
              env:
                APP_URL: "https://{{ .Release.Name }}.${BASE_DOMAIN}/"
