apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: minio
  namespace: storage
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: enabled
spec:
  interval: 15m
  chart:
    spec:
      chart: minio
      version: 14.1.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: minio-config
      valuesKey: MINIO_USER
      targetPath: MINIO_USER
    - kind: ConfigMap
      name: minio-config
      valuesKey: MINIO_PASSWORD
      targetPath: MINIO_PASSWORD
  values:
    global:
      fallbackDefaults:
        storageClass: "truenas-iscsi-api-csi"

    service:
      api:
        type: NodePort
        ports:
          api:
            enabled: true
            targetPort: 10106
            nodePort: 30106
            port: 10106

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                MINIO_ROOT_USER: "{{ .Values.MINIO_USER }}"
                # MINIO_BROWSER_REDIRECT_URL: ""
                # MINIO_SERVER_URL: ""
                MINIO_ROOT_PASSWORD: "{{ .Values.MINIO_PASSWORD }}"

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: minio.elite.internal
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: selfsigned
