apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ark-scorched
  namespace: games
spec:
  interval: 5m
  timeout: 30m
  chart:
    spec:
      chart: ./charts/ark-sa
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: game-config
      valuesKey: ark_scorched_lb_ip
      targetPath: spec.values.service.loadBalancerIP
      optional: false
    - kind: ConfigMap
      name: game-config
      valuesKey: RCON_PASSWORD
      targetPath: spec.values.server.adminPassword
      optional: false
    - kind: ConfigMap
      name: game-config
      valuesKey: GAME_PASSWORD
      targetPath: spec.values.server.password
      optional: false
  values:
    server:
      name: "Venture Bros (Scorched Earth)"
      map: ScorchedEarth_WP
      clusterID: venturecluster
    service:
      type: LoadBalancer
      gamePort: 7777
      peerPort: 7778
      queryPort: 27015
    persistence:
      cluster:
        existingClaim: ark-cluster-shared
      steamcmd:
        existingClaim: ark-steamcmd-shared
