apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ark-scorched
  namespace: games
spec:
  interval: 5m
  timeout: 30m
  chart:
    spec:
      chart: charts/stable/arksurvivalascended
      sourceRef:
        kind: GitRepository
        name: fosscharts
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: game-config
      valuesKey: ark_scorched_lb_ip
      targetPath: spec.values.service.main.loadBalancerIP
      optional: false
    - kind: ConfigMap
      name: ark-shared-config
      valuesKey: cluster-env.yaml
      targetPath: spec.values.workload.main.podSpec.containers.main.env
      optional: false
  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                MOTD: "Welcome to Venture Bros Scorched Earth!"
                MAP_NAME: "ScorchedEarth_WP"
                SESSION_NAME: "Venture-Bros (Scorched Earth)"
    # persistence:
    #   game:
    #     existingClaim: ark-scorched-game
    #   base:
    #     existingClaim: ark-cluster-shared
    #   cluster:
    #     existingClaim: ark-steamcmd-shared
    #   save:
    #     existingClaim: ark-scorched-save
