apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ark-island
  namespace: games
spec:
  interval: 5m
  releaseName: ark-island
  chart:
    spec:
      chart: ./charts/ark-sa
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    server:
      name: IslandServer
      password: pass123
      adminPassword: adminpass
      map: TheIsland_WP
    service:
      type: LoadBalancer
    persistence:
      ark:
        existingClaim: ark-cluster-shared
      steamcmd:
        existingClaim: ark-steamcmd-shared
