apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  chart:
    spec:
      chart: mosquitto
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      version: 17.3.4
  interval: 1m0s
  timeout: 15m0s
  values:
    global:
      fallbackDefaults:
        storageClass: "longhorn"
        pvcRetain: false
        pvcSize: 10Gi
    persistence:
      configinc:
        size: 1Gi
    service:
      main:
        type: LoadBalancer
