apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: infrastructure
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.23.2
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: false
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    crds:
      create: true
    # This is an example structure, the exact keys might vary slightly
    # with chart version 0.23.2 but are generally under 'admission' or 'webhook'
    admission:
      create: true # This might be a master switch for all admission related resources
      # OR more granularly:
    webhook:
      mutating:
        create: true
      validating:
        create: true
    # Sometimes it's also seen as:
    # createAdmissionWebhooks: true
    # or similar.