apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actual
  namespace: web-services
spec:
  chart:
    spec:
      chart: actualserver
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      version: 13.5.0
  interval: 1m0s
  timeout: 10m0s
  valuesFrom:
    - kind: ConfigMap
      name: web-secrets
      valuesKey: BASE_DOMAIN
      targetPath: BASE_DOMAIN
  values:
    # https://artifacthub.io/packages/helm/community-charts/actualbudget
    persistence:
      data:
        enabled: true
        storageClass: truenas-iscsi-api-csi
        size: 10Gi
        accessModes:
          - ReadWriteOnce
        retain: true
        # existingClaim: "pvc-ffc507ea-f793-43bf-9f50-d1c11707e067"
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: "{{ .Release.Name }}.{{ .Values.BASE_DOMAIN }}"
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: thefoss-le-prod
          homepage:
            enabled: true
            group: "Services"
