apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actual
  namespace: web-services
spec:
  chart:
    spec:
      chart: actual
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      version: 13.5.0
  interval: 1m0s
  timeout: 10m0s
  values:
    # https://artifacthub.io/packages/helm/community-charts/actualbudget
    persistence:
      data:
        enabled: true
        storageClass: truenas-nfs-csi
        size: 10Gi
        accessModes:
          - ReadWriteOnce
        retain: true
        # existingClaim: "actual-budget-data"
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: "{{ .Release.Name }}.${BASE_DOMAIN}"
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: thefoss-le-prod
          homepage:
            enabled: true
            group: "Services"
