apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ark-ragnarok
  namespace: games
spec:
  interval: 5m
  timeout: 30m
  chart:
    spec:
      chart: charts/stable/arksurvivalascended
      # version: 0.1.1
      sourceRef:
        kind: GitRepository
        name: fosscharts
        namespace: flux-system
      interval: 5m
  upgrade:
    remediation:
      remediateLastFailure: false
  values:
    # TZ: "America/Los_Angeles"
    service:
      main:
        type: LoadBalancer
        ports:
          main:
            port: 7783
          peer:
            port: 7784
      steam:
        ports:
          query:
            port: 27018

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                UPDATE_SERVER: "TRUE"  # Enable or disable update checks
                CHECK_FOR_UPDATE_INTERVAL: 1  # Check for Updates interval in hours
                ENABLE_MOTD: "TRUE"
                SERVER_ADMIN_PASSWORD: "VentureTemp123"
                SERVER_PASSWORD: "password"
                MAX_PLAYERS: 6
                CLUSTER_ID: "venturecluster"
                MOD_IDS: "950914,935408"

                MOTD: "Welcome to Venture Bros Ragnarok!"
                MAP_NAME: "Ragnarok_WP"
                SESSION_NAME: "Venture-Bros (Ragnarok)"
