apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud2
  namespace: nextcloud
spec:
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: 34.0.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: false
    crds: CreateReplace
    remediation:
      retries: 3
    timeout: 20m0s
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    global:
      fallbackDefaults:
        # -- Define a storageClassName that will be used for all PVCs
        # Can be overruled per PVC
        storageClass: "truenas-iscsi-api-csi"
        pvcSize: 20Gi
        pvcRetain: false

    image:
      repository: docker.io/library/nextcloud
      pullPolicy: Always
      tag: 30.0.11-fpm@sha256:29f0a0e5bd6957666b264bd4b51785356bbae6239db40bf627eee7ae1fd76fb6

    # credentials:
    #   mys3:
    #     type: s3
    #     url: "${S3_URL}"
    #     bucket: "nextcloud_pgsql"
    #     accessKey: "${S3_ACCESKEY}"
    #     secretKey: "${S3_SECRETKEY}"
    #     # encrKey: "myencryptionkey"


    nextcloud:
      general:
        default_phone_region: US
        accessIP: ${NGINX_EXTERNAL_IP}
      configs:
        instance.config.php: |-
          <?php
          $CONFIG = array (
              'overwrite.cli.url' => 'https://nextcloud.***REMOVED***',
              'overwritehost' => 'nextcloud.***REMOVED***',
              'overwriteprotocol' => 'https',
              'instanceid' => 'oc0eseu24utd',
              'installed' => true,
              'passwordsalt' => 'fP9hj+GgVzmnlIi+AdMsX84/YMJIR6',
              'secret' => '9kXhpzQu/FFuvXKFwAmY6UQgsHyG02uV1rrFMEiDOaVzk0/Q',
              'trusted_domains' =>
              array (
                  0 => '192.168.1.51',
                  0 => '192.168.1.52',
                  0 => '192.168.1.53',
                  0 => '192.168.1.54',
                  0 => '192.168.1.55',
                  1 => 'nextcloud.***REMOVED***',
              ),
              'trusted_proxies' =>
              array (
                  0 => '192.168.1.60',
              ),
              'dbtableprefix' => 'oc_',
              'mysql.utf8mb4' => true,
              'data-fingerprint' => 'f10d1171641028748c4b5df517740b55',
              'default_phone_region' => 'US',
          );

    persistence:
      data:
        size: 2T
        storageClass: truenas-nfs-api-csi
        retain: true
        accessModes:
          - ReadWriteMany
        # existingClaim: pvc-4bf0acbd-f255-425e-9ab7-a422dec76d16
      html:
        storageClass: longhorn
        accessModes:
          - ReadWriteMany
      config:
        storageClass: longhorn
        accessModes:
          - ReadWriteMany

    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: "{{ .Release.Name }}.${BASE_DOMAIN}"
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: thefoss-le-stage
        homepage:
          enabled: true
          group: "Services"

    # redis:
    #   enabled: false

