apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud2
  namespace: nextcloud
spec:
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: 34.0.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: false
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    nextcloud:
      credentials:
        # An admin username needs to be set
        initialAdminUser: admin
        # An admin password needs to be set.
        initialAdminPassword: somepassword
      general:
        # The default phone region needs to be set (if you are unsure about your region, you can find your code for your region in this [wiki](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements))
        default_phone_region: US
        # You must set `accessIP` to the ip address used by _Traefik_
        accessIP: 192.168.0.10

    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: "{{ .Release.Name }}.${BASE_DOMAIN}"
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: thefoss-le-prod
