apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 30m
  timeout: 20m
  chart:
    spec:
      chart: nextcloud
      version: ^40.0.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 60m
  install:
    createNamespace: false
    timeout: 45m
  upgrade:
    timeout: 45m
  valuesFrom:
    - kind: ConfigMap
      name: nextcloud-configs
      valuesKey: values.yaml
      optional: false
  values:
    # https://truecharts.org/truetech/truecharts/charts/stable/nextcloud/
    global:
      fallbackDefaults:
        # -- Define a storageClassName that will be used for all PVCs
        # Can be overruled per PVC
        storageClass: "longhorn"
        pvcSize: 10Gi
        pvcRetain: false
        accessModes:
        - ReadWriteMany
    workload:
      # Nextcloud php-fpm
      main:
        podSpec:
          containers:
            main:
              env:
                TRUSTED_PROXIES: "10.0.0.0/8"
                FORWARDED_FOR_HEADERS: '["HTTP_X_FORWARDED_FOR"]'
              probes:
                startup:
                  spec:
                    failureThreshold: 1200
    nextcloud:
      general:
        default_phone_region: US
      previews:
        # Casings are important
        # https://github.com/nextcloud/server/blob/master/config/config.sample.php#L1269
        # Only the last part of the provider is needed
        providers:
          - BMP
          - EMF
          - Font
          - GIF
          - HEIC
          - Illustrator
          - ImaginaryPDF
          - JPEG
          - MarkDown
          - Movie
          - MP3
          - MP4
          - MSOffice2003
          - MSOffice2007
          - MSOfficeDoc
          - OpenDocument
          - PDF
          - Photoshop
          - PNG
          - Postscript
          - StarOffice
          - SVG
          - TIFF
          - TXT
          - XBitmap
      clamav:
        enabled: true
      # collabora:
      #   enabled: true
      #   # default|compact|tabbed
      #   interface_mode: default
      #   username: admin
      #   password: "{{ .Values.TEMP_PASSWORD }}"
      #   dictionaries:
      #     - de_DE
      #     - en_GB
      #     - en_US
      #     - el_GR
      #     - es_ES
      #     - fr_FR
      #     - pt_BR
      #     - pt_PT
      #     - it
      #     - nl
      #     - ru
      # onlyoffice:
      #   # It will not deploy the container
      #   # Only add the OnlyOffice settings
      #   enabled: false
      #   url: ""
      #   internal_url: ""
      #   verify_ssl: true
      #   jwt: ""
      #   jwt_header: Authorization
      # configs:
      #   redis.config.php: |-
      #     <?php
      #     $CONFIG = array (
      #         'redis' =>
      #         array (
      #           'host' => 'redis.infrastructure.svc.cluster.local',
      #           'port' => 6379,
      #           'password' => "{{ .Values.REDIS_PASSWORD }}",
      #         ),
      #         'memcache.local' => '\\OC\\Memcache\\APCu',
      #         'memcache.distributed' => '\\OC\\Memcache\\Redis',
      #         'memcache.locking' => '\\OC\\Memcache\\Redis',
      #     );
    persistence:
      data:
        enabled: true
        existingClaim: nextcloud-persistent-data
      html:
        storageClass: longhorn
        accessModes:
          - ReadWriteMany
        size: 2Gi
      config:
        storageClass: longhorn
        accessModes:
          - ReadWriteMany
        size: 1Gi

    cnpg:
      main:
        enabled: true
        storage:
          size: 20Gi
          storageClass: truenas-nfs-api-csi
        walStorage:
          size: 5Gi
          storageClass: longhorn

    ingress:
      main:
        enabled: true
        annotations:
          # For "Request Entity Too Large" errors.
          nginx.org/client-max-body-size: "10G"
          nginx.org/client-body-buffer-size: "400M"
          nginx.org/lb-method: "ip_hash"
        ingressClassName: external
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: thefoss-le-prod
        homepage:
          enabled: true
          group: "Services"

    # redis:
    #   enabled: false
    #   includeCommon: false

