apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud2
  namespace: nextcloud
spec:
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: 34.0.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: false
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    global:
      fallbackDefaults:
        # -- Define a storageClassName that will be used for all PVCs
        # Can be overruled per PVC
        storageClass: "truenas-iscsi-api-csi"
        pvcSize: 20Gi
        pvcRetain: false

    # credentials:
    #   mys3:
    #     type: s3
    #     url: "${S3_URL}"
    #     bucket: "nextcloud_pgsql"
    #     accessKey: "${S3_ACCESKEY}"
    #     secretKey: "${S3_SECRETKEY}"
    #     # encrKey: "myencryptionkey"


    nextcloud:
      general:
        default_phone_region: US
        accessIP: ${NGINX_EXTERNAL_IP}

    persistence:
      data:
        size: 2T
        storageClass: truenas-nfs-api-csi
        retain: true
        accessModes:
          - ReadWriteMany
        # existingClaim: pvc-4bf0acbd-f255-425e-9ab7-a422dec76d16
      html:
        storageClass: longhorn
        accessModes:
          - ReadWriteMany
      config:
        storageClass: longhorn
        accessModes:
          - ReadWriteMany

    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: "{{ .Release.Name }}.${BASE_DOMAIN}"
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: thefoss-le-stage
        homepage:
          enabled: true
          group: "Services"

    # redis:
    #   enabled: false

