apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hashtopolis
  namespace: web-services
spec:
  interval: 15m
  timeout: 20m
  chart:
    spec:
      chart: ./charts/hashtopolis
      sourceRef:
        kind: GitRepository
        name: cluster
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: false
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: web-config
      valuesKey: BASE_DOMAIN
      targetPath: BASE_DOMAIN
  values:
    global:
      fallbackDefaults:
        storageClass: "longhorn"
        pvcSize: 10Gi

    mariadb:
      enabled: false

    appConn:
      mariadb:
        enabled: false

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                # MySQL connection settings - use TrueCharts CNPG or MariaDB
                HASHTOPOLIS_DB_HOST: "mariadb.web-services.svc.cluster.local"
                HASHTOPOLIS_DB_PORT: "3306"
                HASHTOPOLIS_DB_NAME: "hash_db"
                HASHTOPOLIS_DB_USER: "hash_user"

                HASHTOPOLIS_DB_PASS: "hash_pass"
                HASHTOPOLIS_DB_DATABASE: "hash_db"
                HASHTOPOLIS_ADMIN_USER: "my_user"
                HASHTOPOLIS_ADMIN_PASSWORD: "my_pass"
                # HASHTOPOLIS_APIV2_ENABLE: $HASHTOPOLIS_APIV2_ENABLE

    persistence:
      files:
        enabled: true
        storageClass: truenas-iscsi-api-csi
        size: 10Gi
        accessModes:
          - ReadWriteOnce
        retain: true
      import:
        enabled: true
        storageClass: truenas-iscsi-api-csi
        size: 5Gi
        accessModes:
          - ReadWriteOnce
        retain: true

    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: "{{ .Release.Name }}.${BASE_DOMAIN}"
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: thefoss-le-prod
          homepage:
            enabled: true
            group: "Services"
