apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-cluster-shared
  namespace: games
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: truenas-nfs-api-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-steamcmd-shared
  namespace: games
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: truenas-nfs-api-csi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ark-shared-config
  namespace: games
data:
  # Single YAML block containing shared env vars
  cluster-env.yaml: |
    CLUSTER_ID: venturecluster
    MAX_PLAYERS: 6
    UPDATE_SERVER: "TRUE"
    CHECK_FOR_UPDATE_INTERVAL: 1
    ENABLE_MOTD: "TRUE"
    SERVER_ADMIN_PASSWORD: "VentureTemp123"
    SERVER_PASSWORD: "password"
