apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-cluster-shared
  namespace: games
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: truenas-nfs-api-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-steamcmd-shared
  namespace: games
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: truenas-nfs-api-csi
