apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ark-aberration
  namespace: flux-system
spec:
  interval: 10m
  path: apps/games/ark-aberration/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
