apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bad-employee
  namespace: flux-system
spec:
  interval: 10m
  path: apps/default/bad-employee/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
