apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apt-cacher-ng
  namespace: flux-system
spec:
  interval: 10m
  path: apps/mirrors/apt-cacher-ng/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
