apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vpn
  namespace: flux-system
spec:
  interval: 10m
  path: apps/web-services/vpn/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
