apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: transmission
  namespace: torrents
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: enabled
spec:
  interval: 15m
  chart:
    spec:
      chart: transmission
      version: ^24.0.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: torrents-config
      valuesKey: BASE_DOMAIN
      targetPath: BASE_DOMAIN
      optional: false
    - kind: ConfigMap
      name: vpn-addon-config
      valuesKey: addons.yaml
  values:
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 1Gi
      media:
        enabled: true
        type: nfs
        path: /mnt/local-raid/no-backup/dvr
        mountPath: /media
        server: truenas.{{ .Values.BASE_DOMAIN }}

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: transmission.elite.internal
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: selfsigned
