apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lazy-librarian
  namespace: torrents
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: enabled
spec:
  interval: 15m
  chart:
    spec:
      chart: lazylibrarian
      version: 21.1.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  valuesFrom:
    - kind: ConfigMap
      name: torrents-config
      valuesKey: BASE_DOMAIN
      targetPath: BASE_DOMAIN
      optional: false
    - kind: ConfigMap
      name: torrents-config
      valuesKey: HP_API_READARR
      targetPath: ingress.main.integrations.homepage.widget.custom.key
      optional: true
  values:
    TZ: America/Los_Angeles

    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: "{{ .Release.Name }}.{{ .Values.BASE_DOMAIN }}"
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: thefoss-le-prod
          homepage:
            enabled: true
            group: "Torrents"
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 5Gi
      media:
        enabled: true
        type: nfs
        path: /mnt/local-raid/no-backup/dvr
        mountPath: /media
        server: truenas.{{ .Values.BASE_DOMAIN }}
