apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prowlarr
  namespace: flux-system
spec:
  interval: 10m
  path: apps/torrents/prowlarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  postBuild:
    substitute:
      BASE_DOMAIN: ***REMOVED***
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
