apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lazy-librarian
  namespace: flux-system
spec:
  interval: 10m
  path: apps/torrents/lazy-librarian/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
