apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgresql
  namespace: flux-system
spec:
  interval: 10m
  path: apps/web-services/postgresql/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
