apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minecraft-router
  namespace: flux-system
spec:
  interval: 10m
  path: apps/games/minecraft-router/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
