apiVersion: v1
kind: ConfigMap
metadata:
    name: infrastructure-config
    namespace: infrastructure
data:
    BASE_DOMAIN: ENC[AES256_GCM,data:bjSigNtrX9em1iA=,iv:ZQVHuHNEuhnnpgU4CUZOYniVfeSb8eWheG2G4JF5vDk=,tag:r1fjYzW3DdjhbzuM3IcGBw==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:xhgMVSmNGm53YSkV89FClGYGTJC0hD3dnrsVlYB9EFtg0Vba+qioCw==,iv:zpTqRJ/VGdB9fNy3e9ns+U0+CUYhzrye4zyYWffmvjg=,tag:ppIpd+Hy/ejKY4KuxbTGYg==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:Lz0GjsKFauWQ2wSdJ8nz,iv:/bCkek3KV2P4PVU9bJMzVRUFbH2cXSBZGKor4KxOwxM=,tag:mUXeBIFCcFnk0aNPsAt7Vw==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:ZqA0CpZI08iHtJS6ymcSdAur1Dw=,iv:0UcWT+6BPn2m2lzpo95Xzl5tVIY4YcHkLjkmbpOy94Y=,tag:ZSXTjGB/Mig2fUD2bZlypw==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdjJQVTA1RG1GcDlUQWxI
            Tlg4MWM3ZmxwNHhhRHo0WFVSYXNpa1VwVkhvCnpBWHlpS1hMaGcwVDVnNHQ4RytI
            QVlNWngwSjZpazEzcVl4MER0MWtzcUEKLS0tIGVWc1A2NUcra3E0cDZoVmx5V01k
            bHhTeFVRM2FBL1pTd3FMTUphUDFzTzgKw9Qh5N2Mj9nuk20vbFK7di3UT6jnjSvG
            y2Y9wMUWpeLjSMkbP/jTusXVv5EO0/3mWS6dkYr6QzvBFGMQIWphEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-12T06:24:05Z"
    mac: ENC[AES256_GCM,data:zXLMuwHr4rzbXZsR6N9m3uTqlJPhgfa2TMMn9RaxmeIQZ1YRLNQv33fw8TyU/Zg0isn4XiYjDQp5C4RGnQuNhMZ9+RRjfzmEBTVH7be1aK0PU9kqclK7BXWXg8OB983BuhU+hJCxm1/OGRAbK9RynbcbLdTvBFucHDuazh44dGE=,iv:W29iJsGtr4bQr9UkPNJDoo/peR1PSLbZEYagpIfDte8=,tag:jGBHJDuYoevDmTywUiMzqg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
