apiVersion: v1
kind: Secret
metadata:
    name: infrastructure-secrets
    namespace: infrastructure
type: Opaque
stringData:
    BASE_DOMAIN: ENC[AES256_GCM,data:dVS/CY5UshhR2/E=,iv:OXjKOudD6nfaYDiYFL8FrlnE6sFD34V9dpfWCm+IMvs=,tag:gDAcjAvpigbp8KaAX2nDhQ==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:Qf8EF+pyBcUOhwA8c0hqqlyojbHygwHMZOVqFddTWPPELX/G/8BAZQ==,iv:jrhZCwMzZ0BE0QQlkM4dqerHyjFUcWgVZiPGiMKmO8k=,tag:s94GX3H0uoRi0u2yXzcWOg==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:3AtPEOShFQt7S8rDpSCr,iv:EKhLbLdnTJ2WfcDaJbiyGuaFYqpH3+gSNLm43TkKvvU=,tag:P1MJ3Ve3Em570/QoiuX4ZA==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:i52Mk/23O+Rieg89ASa0VBzGpF4=,iv:yFBh6uRo5udRaVnZYJh9eveuMaNdnnmE1mFcjiwRQ28=,tag:ZqAb9tN3DnptYpd6kQSmeA==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdjJQVTA1RG1GcDlUQWxI
            Tlg4MWM3ZmxwNHhhRHo0WFVSYXNpa1VwVkhvCnpBWHlpS1hMaGcwVDVnNHQ4RytI
            QVlNWngwSjZpazEzcVl4MER0MWtzcUEKLS0tIGVWc1A2NUcra3E0cDZoVmx5V01k
            bHhTeFVRM2FBL1pTd3FMTUphUDFzTzgKw9Qh5N2Mj9nuk20vbFK7di3UT6jnjSvG
            y2Y9wMUWpeLjSMkbP/jTusXVv5EO0/3mWS6dkYr6QzvBFGMQIWphEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-10T15:48:44Z"
    mac: ENC[AES256_GCM,data:WTm74AMBz0ILVuOEGWl+ARheL6tXVVGdZo2nKWjn3ukVvikQmKOrmPlIyJ1j8+nGNyW3HvoXOtRWZn8Y7KqRTF4i69tEICLop0y1/1m6B7YF2rEbv1I4B+oxMtEnbSPbq73XSJSuTAgleg2SIZRJquS6CxsQMRPluiY09lGeABE=,iv:7FDIKPwh+nU4zWCdIyKYA5Fn5rZzb7CYF7AzFx65eJs=,tag:98C9JQqh/QjmbVLW9hzumQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
