apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: le-prod
  namespace: flux-system
spec:
  interval: 10m
  path: apps/infrastructure/le-prod/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster