apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: decryption
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: cluster
  path: ./apps
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
