apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-box
  namespace: flux-system
spec:
  interval: 10m
  path: apps/development/dev-box/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
