apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-ddns
  namespace: infrastructure
spec:
  chart:
    spec:
      chart: cloudflareddns
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      version: 11.5.11
  interval: 1m0s
  timeout: 10m0s
  valuesFrom:
    - kind: ConfigMap
      name: infrastructure-config
      valuesKey: BASE_DOMAIN
      targetPath: BASE_DOMAIN
    - kind: ConfigMap
      name: infrastructure-config
      valuesKey: DOMAIN_0_CLOUDFLARE_TOKEN
      targetPath: cloudflareddns.api_token
  values:
    # https://truecharts.org/charts/stable/cloudflareddns
    cloudflareddns:
      host_zone_record:
        - domain: ${BASE_DOMAIN}
          record: A
          zone: ${BASE_DOMAIN}
    workload:
      main:
        strategy: Recreate
    persistence:
      config:
        type: emptyDir
        medium: Memory
        size: 2Gi
