apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 10m
  path: apps/storage/minio/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster