apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ark-aberration
  namespace: games
spec:
  interval: 5m
  timeout: 30m
  chart:
    spec:
      chart: ./charts/ark-sa
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: game-config
      valuesKey: ark_aberration_lb_ip
      targetPath: spec.values.service.loadBalancerIP
      optional: false
    - kind: ConfigMap
      name: game-config
      valuesKey: RCON_PASSWORD
      targetPath: spec.values.server.adminPassword
      optional: false
    - kind: ConfigMap
      name: game-config
      valuesKey: GAME_PASSWORD
      targetPath: spec.values.server.password
      optional: false
  values:
    server:
      name: "Venture-Bros-Aberration"
      map: Aberration_WP
      clusterID: venturecluster
      mods: [950914, 935408]  # Awesome Teleporters!, Der Dino Finder
    service:
      type: LoadBalancer
      gamePort: 7781
      peerPort: 7782
      queryPort: 27017
    persistence:
      ark:
        existingClaim: ark-aberration-game
      cluster:
        existingClaim: ark-cluster-shared
      steamcmd:
        existingClaim: ark-steamcmd-shared
