apiVersion: v1
kind: Secret
metadata:
    name: gitlab-agent-token
    namespace: gitlab-agent
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:imsBsQ7NSHEAHaEIKnzGoVmjcnQ1XDZuVZP657So34bC0ITjYgyARE2QynIZe9qDbTRKeMXu3Q==,iv:4n3rfXhF74ScHlnX5dMZ+fk+eB4BJZn5vYc29GVQ280=,tag:3Ifn+O7KlZQJHxpWkI6Erw==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRWhGSWF6OHNtVmJydWlu
            WEtVbGlYUEVZamt3QitFeUREK29aQVloN0hFCkpLV0xud01zZ2JmbG45clpEb291
            NmNRL2lONDJ5VEhEU3g0SXlLdG5GaUkKLS0tIENOeEVRV2ZaL3RQL2o1bmJieCtV
            LzY0dUVXSUVEaC92RG9jQU9xTHErdWsKxi3frEAC8vFZYAm/kg8ZlhcS0H81GuT/
            rYzpeQamF1H/SSiIveeiB+Yxs7qbkLS9LQkNPPNP42vKVSv2pNm+eA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T23:37:41Z"
    mac: ENC[AES256_GCM,data:JnGCtdLXPVPz+nl0vAm/qNC36KvlJRJy9H6zIWh0rSH/cocfN9dEsL1fxcXJFf+2a00hRUiHKSL+eAwqFlN0jWtfmuwUa9YQuRh1VyWgVIaTGUDocww2KgTqkfQIp5TAtamQQfl0c+tLAEGCtZ7Gia2npZMErnUpVsmBecWG8bE=,iv:A9Ws39JF62l+rMrUUk3PtW1csDant/FmDE72Y8dsVGw=,tag:50mbI6hJwbuS2b6Y9qNfMg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
