{{- if .Values.updates.restartJob.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "development-workspace.fullname" . }}-restarter
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - patch
{{- end }}
